/**
 ****************************************************************************************************
 * @file        shell_uart.c
 * @brief       DBCOM(rs232调试串口，default usart1,printf) 和 普通usart uart 串口驱动
 * @author      EDWOY
 * @version     V1.5 verified
 * @date        2023.5.13 
 * @license     Copyright (c) 2020-2038, 
 ****************************************************************************************************
 * @attention
 *    -1-，dbcom的接收中断和fgetc是互斥的，只能二选一
      -2-, __use_no_semihosting and delate'Use microLIB' of Target->Options
			   2.1 fputc-printf，must add "FILE __stdout"
				 2.2 fgetc-getchr(),must add "FILE __stdin"
				     if enable rx-interrupt of dbcom , fgetc-getchar() can`t be used
		  -3-,dbcom
			   3.1 XCOM2.7无论有没有勾选"发送新行"，它都会在字符串末尾自动加上回车换行符 "\r\n"
			   3.2 SSCOM 则需要勾选"加回车换行符"， 发送到dbcom的数据，才能在mcu dbcom的 rx 中断处理函数中
					 存入 g_dbcom_rxbuff
				 3.3 DBCOM doesn't storage "\r\n" to g_dbcom_rxbuff	 
      -4-,based on
			   4.1 use usart.h/c generated by cubemx
				 4.2 add res_uart.h/c , shell_uart.h/c
         4.3 in convert_path.h,UART_HEAD is defined to EDW_UART_HEAD 				 
 ****************************************************************************************************
 * 实验平台：
       1 ATK-DMFSTM32F407IGT6

 ****************************************************************************************************
 * @update
   V1.5 2023.5.13 verified
        g_dbcom_rx_sta --> g_dbcom_rx_curcnt	 
				void DBCOM_UX_IRQHandler(void)
   V1.4  2023.4.29,verified,
	    if(g_dbcom_rx_curcnt & 0x8000)--->if(True == g_dbcom_rxtkn_ovr)
   V1.3 2023.3.1,verified,
	     [+]  g_dbcom_rxtkn & g_dbcom_rxtkn_ovr in  DBCOM_UX_IRQHandler
   V1.2 2023.2.26 verified
	      Fill rx-datas in DBCOM_UX_IRQHandler
   V1.1 20221214 ,
	    [+] FILE __stdin; fgetc(FILE* f); but Non use it(because dbcom_rx`s interrupt is enable)
 * V1.0 20211014
 * 第一次发布
 * 
 ****************************************************************************************************
 */
#include "ThisProj_Glb.h"
#include SYS_HEAD   //"./SYSTEM/sys/sys.h"
#include UART_HEAD
#include DLY_HEAD
#include LED_HEAD


/* 如果使用OS,则包括下面的头文件即可 */
#if OS_EN_UCOS
#include "includes.h"                               /* OS 使用 */
#endif

///---Nonuse_MicroLib-------------------------------------------------------------------------------------------
//Notice : Options -->Target, Delate the Use-MicroLIB and C/C++ add _Nonuse_MicroLib_
#ifndef _Nonuse_MicroLib_
#define _Nonuse_MicroLib_
#endif

#ifdef _Nonuse_MicroLib_
#if (__ARMCC_VERSION >= 6010050)            /* 使用AC6编译器时 */
__asm(".global __use_no_semihosting\n\t"); /* 声明不使用半主机模式 */
__asm(".global __ARM_use_no_argv \n\t");   /* AC6下需要声明main函数为无参数格式，否则部分例程可能出现半主机模式 */

#else
/* 使用AC5编译器时, 要在这里定义__FILE 和 不使用半主机模式 */
#pragma import(__use_no_semihosting)

struct __FILE
{
    int handle;
    /* Whatever you require here. If the only file you are using is */
    /* standard output using printf() for debugging, no file handling */
    /* is required. */
};

#endif //<#if _Nonuse_MicroLib_>

/* 不使用半主机模式，至少需要重定义_ttywrch\_sys_exit\_sys_command_string函数,以同时兼容AC6和AC5模式 */
int _ttywrch(int ch)
{
    ch = ch;
    return ch;
}

/* 定义_sys_exit()以避免使用半主机模式 */
void _sys_exit(int x)
{
    x = x;
}

char *_sys_command_string(char *cmd, int len)
{
    return NULL;
}

/* FILE 在 stdio.h里面定义. */
FILE __stdout;

//redefine fputc函数, printf函数最终会通过调用fputc输出字符串到串口 
int fputc(int ch, FILE *f)
{
    while(RESET == __HAL_UART_GET_FLAG(&g_dbcom_hdr, UART_FLAG_TC));
		HAL_UART_Transmit(&g_dbcom_hdr, (uint8_t *)&ch, 1, 200);	
	
    return ch;
}
#endif
/**dbcom的接收中断已经使能，dbcom rx-interrupt和fgetc冲突
  则必须禁用fgetc

  ****************
FILE __stdin;
//redefine fgetc function used when dbcom is disable
int fgetc(FILE* f)
{
	int rev;

	HAL_UART_Receive(&Hdr_DBCOM,(uint8_t*)&rev,1,300);

	return rev;
}
**********************************************************/
///---END,Nonuse_MicroLib------------------------------------------------------------------------------End-----
    
#if DBCOM_EN_RX        /* 如果使能了接收 */

/**
 * @brief       串口X初始化函数(from ATK-motor)
                verified and valid,  but don't use it
 * @param       baudrate: 波特率, 根据自己需要设置波特率值
 * @note        注意: 必须设置正确的时钟源, 否则串口波特率就会设置异常.
 *              这里的USART的时钟源在sys_stm32_clock_init()函数中已经设置过了.
 * @retval      无
 */
void dbcom_init(uint32_t baudrate)
{
    g_dbcom_hdr.Instance = DBCOM_UX;                         /* USART1 */
    g_dbcom_hdr.Init.BaudRate = baudrate;                    /* 波特率 */
    g_dbcom_hdr.Init.WordLength = UART_WORDLENGTH_8B;        /* 字长为8位数据格式 */
    g_dbcom_hdr.Init.StopBits = UART_STOPBITS_1;             /* 一个停止位 */
    g_dbcom_hdr.Init.Parity = UART_PARITY_NONE;              /* 无奇偶校验位 */
    g_dbcom_hdr.Init.HwFlowCtl = UART_HWCONTROL_NONE;        /* 无硬件流控 */
    g_dbcom_hdr.Init.Mode = UART_MODE_TX_RX;                 /* 收发模式 */
    HAL_UART_Init(&g_dbcom_hdr);                             /* HAL_UART_Init()会使能UART1 */

    /* 该函数会开启接收中断：标志位UART_IT_RXNE，并且设置接收缓冲以及接收缓冲接收最大数据量 */
    HAL_UART_Receive_IT(&g_dbcom_hdr, (uint8_t *)g_dbcom_rx_hdbuf, HdBuf_Size);
	  app_dbcom_rst();
}


/********************************************************
 * @brief   dbcom 中断服务函数 by ATK-MtrCtrl
 
 * @param   void
 * @retval  void
 * @notice 
      -1-,DBCOM rx over,when dbcom->rx receives "\r\n"(0x0D0A) continuously , 
          g_dbcom_rxtkn_ovr = True
      -2-,DBCOM doesn't storage "\r\n" to g_dbcom_rxbuff
 * @update   
      2023.5.13 verified
         1,g_dbcom_rx_sta --> g_dbcom_rx_curcnt
         2, Delate the g_dbcom_rx_sta `s bit14 & bit15
 *********************************************************/
void DBCOM_UX_IRQHandler(void)
{ 
    static uint32_t timeout = 0;
    __I uint32_t maxDelay = 0x1FFFF;
    
#if OS_EN_UCOS                              /* 使用OS */
    OSIntEnter();    
#endif

    HAL_UART_IRQHandler(&g_dbcom_hdr);       /* 调用HAL库中断处理公用函数 */

    timeout = 0;
    while (HAL_UART_GetState(&g_dbcom_hdr) != HAL_UART_STATE_READY) /* 等待就绪 */
    {
        timeout++;                              /* 超时处理 */
        if(timeout > maxDelay)
        {
            break;
        }
    }
     
    timeout=0;
    
    /* 一次处理完成之后，重新开启中断并设置RxXferCount为1 */
    while (HAL_UART_Receive_IT(&g_dbcom_hdr, (uint8_t *)g_dbcom_rx_hdbuf, HdBuf_Size) != HAL_OK)
    {
        timeout++;                              /* 超时处理 */
        if (timeout > maxDelay)
        {
            break;
        }
    }

#if CMPL_DBCOM_RxInt == CMPL_DBCOM_RxInt_Edw	
//verified		
    g_dbcom_rxtkn = True;
		static __IO Bool tmpRxTkn_1st = False;
		if(False == g_dbcom_rxtkn_ovr)      // 接收未完成,即未接受到"\r\n"
		{
				if(True == tmpRxTkn_1st){   // 接收到了0x0d,即接受到'\r'
						if(g_dbcom_rx_hdbuf[0] != 0x0a) {  
							 __NOP();  	
							
						}else {  // 接收到了0x0a,即接受到'\n',亦即连续接收到"\r\n"
							  g_dbcom_rxtkn_ovr = True;	  //edwoy-code		
		
						}
						tmpRxTkn_1st  = False;
						
				}else{   //还没收到0X0D,'\r'
				
						if(g_dbcom_rx_hdbuf[0] == 0x0d){ 
							  tmpRxTkn_1st = True;
							
						}else{
								g_dbcom_rxbuff[g_dbcom_rx_curcnt++] = g_dbcom_rx_hdbuf[0] ;
								if(g_dbcom_rx_curcnt > (DBCOM_REC_LEN - 1))
								{
										g_dbcom_rx_curcnt = 0;     //接收数据错误,重新开始接收 
									  g_dbcom_rxtkn     = False; //edwoy-code	
								    g_dbcom_rxtkn_ovr = False; //edwoy-code		
									  tmpRxTkn_1st      = False;									
								}
						}
				}
		} //<if(False == g_dbcom_rxtkn_ovr)>		
#endif //<#if CMPL_DBCOM_RxInt == CMPL_DBCOM_RxInt_Edw>

#if OS_EN_UCOS    /* 使用uCOS */
    OSIntExit();
#endif

} //<void DBCOM_UX_IRQHandler(void)>
		
/**
 * @brief   Rx传输回调函数
 * @param    huart: UART句柄类型指针
 * @notice
       -2-, [+] g_rs485d1_hdr
       -1-, dbcom rx 接收到了换行符 "\r\n"，是不存入 g_dbcom_rxbuff的 
 * @retval      无
 */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{	
#if CMPL_DBCOM_RxInt == CMPL_DBCOM_RxInt_Atk	
    if(huart->Instance == DBCOM_UX)             /* 如果是串口1 */
    {
        if((g_dbcom_rx_curcnt & 0x8000) == 0)      /* 接收未完成 */
        {
            if(g_dbcom_rx_curcnt & 0x4000)         /* 接收到了0x0d */
            {
                if(g_dbcom_rx_hdbuf[0] != 0x0a) 
                {
                    g_dbcom_rx_curcnt = 0;         /* 接收错误,重新开始 */
                }
                else 
                {
                    g_dbcom_rx_curcnt |= 0x8000;   /* 接收完成了 */
                }
            }
            else                                /* 还没收到0X0D */
            {
                if(g_dbcom_rx_hdbuf[0] == 0x0d)
                {
                    g_dbcom_rx_curcnt |= 0x4000;
                }
                else
                {
                    g_dbcom_rxbuff[g_dbcom_rx_curcnt & 0X3FFF] = g_dbcom_rx_hdbuf[0] ;
                    g_dbcom_rx_curcnt++;
                    if(g_dbcom_rx_curcnt > (DBCOM_REC_LEN - 1))
                    {
                        g_dbcom_rx_curcnt = 0;     /* 接收数据错误,重新开始接收 */
                    }
                }
            }
        }
    } //<if(huart->Instance == DBCOM_UX) >
#endif //<#if CMPL_DBCOM_RxInt == CMPL_DBCOM_RxInt_Atk	>
		
//--CodesAdding edwoy-------------------------------------------------------------------
#if CMPL_RS485d1_RxInt  == CMPL_RS485d1_RxInt_Edw	
//verified
		if(huart->Instance == g_rs485d1_hdr.Instance)
		{     	
      if(g_rs485d1_rx_curcnt < RS485d1_REC_LEN)  		
		     g_rs485d1_rxbuff[g_rs485d1_rx_curcnt++] = g_rs485d1_rx_hdbuf[0] ;
		
		  if(g_rs485d1_rxtkn == False)
 				 g_rs485d1_rxtkn  = True;			
		}
#endif //<#if CMPL_RS485d1_RxInt  == CMPL_RS485d1_RxInt_Edw	>	
//--End,CodesAdding edwoy------------------------------------------------------End------		
} //<void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)>


#endif //<#if DBCOM_EN_RX >

///====CodesAdding edwoy===========================================================================
///----DBCOM--------------------------------------------------------------------DBCOM------
/*************************************************************************
 * @brief  Reset dbcom`s rx(clear rxbuff and reset token)
 * @state  verified 
 * @note  
 * @param  void
 * @retval void
 * @update
       -v1.1-,verified,2023.3.12
            clear g_dbcom_rx_hdbuf[]
       -v1.0-,orgn
 *-----------------bkcode1----------------------

 ************************************************************************/
void app_dbcom_rst(void)
{
   g_dbcom_rx_curcnt = 0;  // 清除接收状态标记 
	 g_dbcom_rxtkn     = False;
	 g_dbcom_rxtkn_ovr = False;
	 g_dbcom_rx_hdbuf[HdBuf_Size - 1] = 0;
	 memset(g_dbcom_rxbuff,0,DBCOM_REC_LEN); //clear dbcom`s rxdatas_buff
}

/**
 * @brief  nonblock dbcom rx datas in poll with interrupt
 * @state  verified and valid
 * @note  
       -1-,Test with XCOM2.7
 * @param  void
 * @retval void
 *******bkcode*********
			  int tmp = strcmp((char*)g_dbcom_rxbuff,"Delate task1");
			  printf("\r\ntmp = %d, <%s>\r\n\r\n",tmp,(char*)g_dbcom_rxbuff);
			  app_dbcom_rst();
 */
void app_dbcom_rxpoll_it(void)
{
   static uint8_t len;
   static uv16_t times = 0;
//	 if(g_dbcom_rx_curcnt & 0x8000) {        /* 接收到了数据? */
	 if(True == g_dbcom_rxtkn_ovr){
				len = g_dbcom_rx_curcnt & 0x3fff;  /* 得到此次接收到的数据长度 */
				printf("\r\n您发送的消息为:\r\n");

				HAL_UART_Transmit(&g_dbcom_hdr, (uint8_t*)g_dbcom_rxbuff, len, 1000);    /*发送接收到的数据*/

				while(RESET == __HAL_UART_GET_FLAG(&g_dbcom_hdr, UART_FLAG_TC));           /*等待发送结束*/
				printf("\r\n\r\n"); 			/* 插入换行 */
			
		    app_dbcom_rst();
		 
		}else{   /* 未接收到了数据? */
				times++;

				if (times % 5000 == 0)
				{
						printf("\r\nEdwoy STM32F429IGTB 串口实验\r\n");
						printf("EDWOY@OUTLOOK.COM\r\n\r\n\r\n");
				}

				if (times % 200 == 0) printf("请输入数据,以回车键结束\r\n");

				if (times % 30  == 0) RED_LED_TGG(); /* 闪烁LED,提示系统正在运行. */

				stkdly_ms(10);
		}	
}

/**
 * @brief  dbcom rx data to handle cmds
 * @state  verified and valid 
 * @note  
       -1-,Test with XCOM2.7
 * @param  void
 * @retval void
 *******bkcode*********
			  int tmp = strcmp((char*)g_dbcom_rxbuff,"Delate task1");
			  printf("\r\ntmp = %d, <%s>\r\n\r\n",tmp,(char*)g_dbcom_rxbuff);
			  app_dbcom_rst();
             HAL_UART_Transmit(&g_dbcom_hdr, (uint8_t*)g_dbcom_rxbuff, len, 1000);
 */
void app_dbcom_cmd_hdr(u8_t* tmpvlu)
{
   static uint8_t len;
   static uv16_t times = 0;

	 if(True == g_dbcom_rxtkn_ovr)  /* 接收到了数据? */
	 {       
				len = g_dbcom_rx_curcnt & 0x3fff;  /* 得到此次接收到的数据长度 */

        printf("\r\n您发送的消息为:\"%s\"\r\n",g_dbcom_rxbuff);
				
				while(__HAL_UART_GET_FLAG(&g_dbcom_hdr, UART_FLAG_TC) != SET);           /*等待发送结束*/
			
				if(NULL == strcmp((char*)g_dbcom_rxbuff,
									 "Exit->>btns-scan<<")){
						*tmpvlu = 0;							 
										 
				 }else if(NULL == strcmp((char*)g_dbcom_rxbuff,
									 "edwmd->>btns-scan<<")){
						*tmpvlu = 1;							
										 
				 }else if(NULL == strcmp((char*)g_dbcom_rxbuff,
									 "atkmd->>btns-scan<<")){
						*tmpvlu = 2;							 
				 }
				 printf("tmpvlu = %d\r\n\r\n",*tmpvlu);					 

				 app_dbcom_rst(); 
		}			
}


void app_dbcom_cmd_hdr2(u8_t* tmpvlu)
{
   static uint8_t len;
   static uv16_t times = 0;
	 if(True == g_dbcom_rxtkn_ovr)  /* 接收到了数据? */
	 {    
				len = g_dbcom_rx_curcnt & 0x3fff;  /* 得到此次接收到的数据长度 */

        printf("\r\n您发送的消息为:\"%s\"\r\n",g_dbcom_rxbuff);
				
				while(SET !=__HAL_UART_GET_FLAG(&g_dbcom_hdr, UART_FLAG_TC)) __NOP();           /*等待发送结束*/
			
			   *tmpvlu = strtoul((char*)g_dbcom_rxbuff,NULL,0); //把字符串转化成 unsigned long 数据
				 printf("tmpvlu = %d\r\n\r\n",*tmpvlu);					 

				 app_dbcom_rst(); 
		}	
}

/**
 * @brief  (default use)DBCOM 初始化,
           verified and valid
 * @param  void
 * @notice
        -1-,必须设置正确的时钟源, 否则串口波特率就会设置异常.
 *          这里的USART的时钟源在sys_stm32_clock_init()函数中已经设置过了.
        -2-,Its all-paras are based on usart.h/c generated by cubemx
            start DBCOM in this way only need HAL_UART_Receive_IT
       
 * @retval void
 */
void app_dbcom_init(void) 
{
//	_dbcom_init(); //== MX_USARTx_UART_Init,defined in usart.c generated by cubemx
	
	// 该函数会开启接收中断：标志位UART_IT_RXNE，并且设置接收缓冲以及接收缓冲接收最大数据量 
	HAL_UART_Receive_IT(&g_dbcom_hdr, (uint8_t *)g_dbcom_rx_hdbuf, HdBuf_Size);
	app_dbcom_rst();	
}
///----End DBCOM-----------------------------------------------------------------End DBCOM-----

/*************************************************************************
 * @brief      uartx 初始化函数
              该函数主要是初始化串口
 * @param     baudrate: 波特率, 根据自己需要设置波特率值
 * @param     sort,uart`s sortnumber defined at ThisProj_Glb.h
 * @retval      无
 * @note  
       -1-,依赖cubemx生成的usart.c中的 MX_USARTx_UART_Init()
           MX_USARTx_UART_Init()完成 USARTx/UARTx的时钟、gpio、参数、nvic的配置
           MX_USARTx_UART_Init() should be before at this func
           
 ************************************************************************/
void app_uart_init(emUartSort_t sort,uint32_t baudrate)
{

}	

/**\brief Reset uart`s rx(clear rxbuff and reset token)
  *\param puart， uart 协议参数组
  *\return void
  *\update
  *    -v1.1-,(verified) 清空rxbuf的长度是rxbuf本身的size大小
  *    -v1.0-,(verified) 清空rxbuf的长度是rxbuf_len
  */
void app_uart_rstrx(emUartSort_t sort)
{
	u16_t len = sizeof(Uarts[sort].rxbuf);

	memset(Uarts[sort].rxbuf,0,len);
	Uarts[sort].rxtkn        = False;	
	Uarts[sort].rxbuf_cnt    = 0;
	Uarts[sort].rxbuf_precnt = 0;
}

/**********************************************************************
  *\brief 自由选择uart端口打印
  *\param uart, uart peripheral
  *\param fmt, 目标打印字符串
  *\return void
  *\notice
       -1-, #include "stdarg.h"	 	
  *\update
  *   -2.0-,()2022.7.7 
         创建单独的txbuf缓存区，替代ptr->rxbuf
  *   -1.0-,(verified) 2022.7.6 created
  *********************************************************************/
void app_free_printf(UART_HandleTypeDef* huart,char* fmt,...)  
{  
//	uart_ppg_t* ptr = &Uarts_ppg[sort];
	u16_t i; 
	u8_t txbuf[256] = {0};
	memset(txbuf,0,256);
	
	va_list ap; 
	va_start(ap,fmt);	
	vsprintf((char*)txbuf,(sc8_t*)fmt,ap);
	va_end(ap);
	i = (u16_t)strlen((const char*)txbuf) ;		//此次发送数据的长度
  HAL_UART_Transmit(huart,txbuf,i,1000);
}

/**
 * @brief  Reset uart`s rx(clear rxbuff and reset token)
 * @state  verified and valid
 * @note  
 * @param  purt
 * @retval void
 *******bkcode*********
 */
//void app_uart_rstrx(uart_para_t *purt)
//{
//	memset(purt->rxbuf,0,purt->rxbuf_len);
//	purt->rxtkn        = False;
//	purt->rxbuf_cnt    = 0;
//	purt->rxbuf_precnt = 0;
//}

///====End CodesAdding edwoy==================================================================End====
 
/* ---Endline:Full File--------------------------------------------------------------All-End------*/
