/**
 ****************************************************************************************************
 * @file        can.h
 * @author      Edwoy
 * @version     V1.0
 * @date        2021-10-27
 * @brief       CAN 驱动代码
 * @license     Copyright (c) 2020-2032, 广州市星翼电子科技有限公司
 ****************************************************************************************************
 * @attention
 *
 * 实验平台：Apollo F429
 * 修改说明
 * V1.0 20211027
 * 第一次发布
 *
 ****************************************************************************************************
 */

#ifndef _SHELL_CAN_H_
#define _SHELL_CAN_H_

#include "ThisProj_Glb.h"
#include "can.h"   //generated by cubemx
#include SYS_HEAD  
#include RES_CAN_HEAD                                       

/* 对外接口函数 */
uint8_t can_receive_msg(uint32_t id, uint8_t *buf);                                     /* CAN接收数据, 查询 */
uint8_t can_send_msg(uint32_t id, uint8_t *msg, uint8_t len);                           /* CAN发送数据 */
uint8_t can_init(uint32_t tsjw,uint32_t tbs2,uint32_t tbs1,uint16_t brp,uint32_t mode); /* CAN初始化 */

///---CodesAdding edwoy------------------------------------------------------------------------------
u8_t  app_can_init(CAN_HandleTypeDef* hcan ,uint32_t mode);
u8_t  app_can_config_ftrbasepara(CAN_HandleTypeDef*, u32_t ftrbk,u32_t ftrmd);
u8_t  app_can_config_ftr16bit(CAN_HandleTypeDef*, u32_t ftrbk,u32_t ftrmd, \
                              u16_t hid,u16_t hmsk,u16_t lid,u16_t lmsk );
u8_t  app_can_config_ftr32bit(CAN_HandleTypeDef*, u32_t ftrbk,u32_t ftrmd,u32_t id,u32_t msk );
u8_t  app_can_msg_tx(CAN_HandleTypeDef* hcan,  u32_t ide, uint32_t id, uint8_t *msg, uint8_t len)	;		
u8_t  app_can_msg_rx(CAN_HandleTypeDef* hcan, uint8_t *buf);
///--End CodesAdding edwoy----------------------------------------------------------------------------

#endif
/* ---Endline:Full File-----------------------------------------------------------------All-End------*/















