/******************************************************************************************************
 * @file        ESP.c
 * @brief       Bluetooth&BLE drive src using serialport(UART/USART)-interface
 * @author      Edwoy
 * @version     V1.0
 * @date        2021-10-27
 * @license     Copyright (c) 2020-2032
 ****************************************************************************************************
 * @attention
       1  Add below int-defs to HAL_UART_MspInit() in usart.c
			      __HAL_UART_ENABLE_IT(uartHandle, UART_IT_RXNE); 
			 2 Basic dependency
					2.1 res_uart.h/c, res_esp_uart.h/c, shell_uart.h/c, usart.h/c(by cubemx)
					2.2 utyBtBle.h/c	
			 3 Esp8266
         3.1 max valid uart-baudrate is 115200bps	
				 3.2 Get the datas returned by bt11 waiting at least 4ms after sending cmd to bt11  
         3.2 Upper(PC-dbcom or cellphone BLEassist app) unlinks,and then links BtBle dev
       4				 
 ****************************************************************************************************
 * @note
 *    1 Default hard
          platform: ATK-DMF407
          module : Esp8266 of LM(www.lbluetooth.com)		
      2 
 ****************************************************************************************************
 * @update
 *   V1.0 20211027 the orgn version from ATK-DMF407
 *
 ****************************************************************************************************
 */
 
#include "ThisProj_Glb.h"
#include CPT_WIFI_HEAD  // "./component/spWiFi/ESP/esp8266.h"
#include DLY_HEAD

//--atk-codes-------------------------------------------------------------------------------
/**
 * @brief       ATK-MW8266D硬件初始化
 * @param       无
 * @retval      无
 */
static void app_esp_rstgpio_init(void)
{
    GPIO_InitTypeDef gpio_init_struct;
    
    WIFI_RST_GPIO_CLK_ENABLE();
    
    gpio_init_struct.Pin   = WIFI_RST_GPIO_PIN;
    gpio_init_struct.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio_init_struct.Pull  = GPIO_NOPULL;
    gpio_init_struct.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(WIFI_RST_GPIO_PORT, &gpio_init_struct);
}

/**
 * @brief       ATK-MW8266D硬件复位
 * @param       无
 * @retval      无
 */
void app_esp_dev_hdrst(void)
{
    WIFI_RST_GPIO(0);
    stkdly_ms(100);
    WIFI_RST_GPIO(1);
    stkdly_ms(500);
}

/**
 * @brief       ATK-MW8266D发送AT指令
 * @param       cmd    : 待发送的AT指令
 *              ack    : 等待的响应
 *              timeout: 等待超时时间
 * @retval      Err_WIFI_NONE     : 函数执行成功
 *              Err_WIFI_TIMEOUT: 等待期望应答超时，函数执行失败
 */
uint8_t app_esp_send_at_cmd(char *cmd, char *ack, uint32_t timeout)
{
    uint8_t *ret = NULL;
    
//    app_atkmodule_uartrx_restart();
	  app_atkmodule_uartrx_rst();
    app_atkmodule_printf("%s\r\n", cmd);
    
    if ((ack == NULL) || (timeout == 0)){
        return Err_WIFI_NONE;
			
    }else{
        while (timeout > 0)
        {
            ret = app_atkmodule_get_uartrx_frame();
            if (ret != NULL)
            {
                if (strstr((const char *)ret, ack) != NULL)
                {
                    return Err_WIFI_NONE;
                }
                else
                {
                    app_atkmodule_uartrx_rst(); //app_atkmodule_uartrx_restart();
                }
            }
            timeout--;
            stkdly_ms(1);
        }
        
        return Err_WIFI_TIMEOUT;
    }
}

/*******************************************************************
 * @brief       ATK-MW8266D初始化
               
 * @param       baudrate: ATK-MW8266D UART通讯波特率
 * @retval      Err_WIFI_NONE  : ATK-MW8266D初始化成功，函数执行成功
 *              Err_WIFI_ERROR: ATK-MW8266D初始化失败，函数执行失败
 * @notice 
       -1-,don`t use app_atkmodule_init(baudrate); 
           if use the codes generated by cubemx
 *********************************************************************/
uint8_t app_esp_init(uint32_t baudrate)
{
    app_esp_rstgpio_init();              /* ATK-MW8266D硬件初始化 */
    app_esp_dev_hdrst();                   /* ATK-MW8266D硬件复位 */
//   app_atkmodule_init(baudrate);       //  ATK-MW8266D UART初始化 
    if (app_esp_at_test() != Err_WIFI_NONE)    /* ATK-MW8266D AT指令测试 */
    {
        return Err_WIFI_ERROR;
    }
    
    return Err_WIFI_NONE;
}

/**
 * @brief       ATK-MW8266D恢复出厂设置
 * @param       无
 * @retval      Err_WIFI_NONE  : 恢复出场设置成功
 *              Err_WIFI_ERROR: 恢复出场设置失败
 */
uint8_t app_esp_restore(void)
{
    uint8_t ret;
    
    ret = app_esp_send_at_cmd("AT+RESTORE", "ready", 3000);
    if (ret == Err_WIFI_NONE)
    {
        return Err_WIFI_NONE;
    }
    else
    {
        return Err_WIFI_ERROR;
    }
}

/**
 * @brief       ATK-MW8266D AT指令测试
 * @param       无
 * @retval      Err_WIFI_NONE  : AT指令测试成功
 *              Err_WIFI_ERROR: AT指令测试失败
 */
uint8_t app_esp_at_test(void)
{
    uint8_t ret;
    uint8_t i;
    
    for (i=0; i<10; i++)
    {
        ret = app_esp_send_at_cmd("AT", "OK", 500);
        if (ret == Err_WIFI_NONE)
        {
            return Err_WIFI_NONE;
        }
    }
    
    return Err_WIFI_ERROR;
}

/**
 * @brief       设置ATK-MW8266D工作模式
 * @param       mode: 1，Station模式
 *                    2，AP模式
 *                    3，AP+Station模式
 * @retval      Err_WIFI_NONE   : 工作模式设置成功
 *              Err_WIFI_ERROR : 工作模式设置失败
 *              Err_WIFI_INVAL: mode参数错误，工作模式设置失败
 */
uint8_t app_esp_set_mode(uint8_t mode)
{
    uint8_t ret;
    
    switch (mode)
    {
        case 1:
        {
            ret = app_esp_send_at_cmd("AT+CWMODE=1", "OK", 500);    /* Station模式 */
            break;
        }
        case 2:
        {
            ret = app_esp_send_at_cmd("AT+CWMODE=2", "OK", 500);    /* AP模式 */
            break;
        }
        case 3:
        {
            ret = app_esp_send_at_cmd("AT+CWMODE=3", "OK", 500);    /* AP+Station模式 */
            break;
        }
        default:
        {
            return Err_WIFI_INVAL;
        }
    }
    
    if (ret == Err_WIFI_NONE)
    {
        return Err_WIFI_NONE;
    }
    else
    {
        return Err_WIFI_ERROR;
    }
}

/**
 * @brief       ATK-MW8266D软件复位
 * @param       无
 * @retval      Err_WIFI_NONE  : 软件复位成功
 *              Err_WIFI_ERROR: 软件复位失败
 */
uint8_t app_esp_dev_reset(void)
{
    uint8_t ret;
    
    ret = app_esp_send_at_cmd("AT+RST", "OK", 500);
    if (ret == Err_WIFI_NONE)
    {
        return Err_WIFI_NONE;
    }
    else
    {
        return Err_WIFI_ERROR;
    }
}

/**
 * @brief       ATK-MW8266D设置回显模式
 * @param       cfg: 0，关闭回显
 *                   1，打开回显
 * @retval      Err_WIFI_NONE  : 设置回显模式成功
 *              Err_WIFI_ERROR: 设置回显模式失败
 */
uint8_t app_esp_ate_config(uint8_t cfg)
{
    uint8_t ret;
    
    switch (cfg)
    {
        case 0:
        {
            ret = app_esp_send_at_cmd("ATE0", "OK", 500);   /* 关闭回显 */
            break;
        }
        case 1:
        {
            ret = app_esp_send_at_cmd("ATE1", "OK", 500);   /* 打开回显 */
            break;
        }
        default:
        {
            return Err_WIFI_INVAL;
        }
    }
    
    if (ret == Err_WIFI_NONE)
    {
        return Err_WIFI_NONE;
    }
    else
    {
        return Err_WIFI_ERROR;
    }
}

/**
 * @brief       ATK-MW8266D连接WIFI
 * @param       ssid: WIFI名称
 *              pwd : WIFI密码
 * @retval      Err_WIFI_NONE  : WIFI连接成功
 *              Err_WIFI_ERROR: WIFI连接失败
 */
uint8_t app_esp_link_ap(char *ssid, char *pwd)
{
    uint8_t ret;
    char cmd[64];
    
    sprintf(cmd, "AT+CWJAP=\"TCP\",\"%s\",\"%s\"", ssid, pwd);
    ret = app_esp_send_at_cmd(cmd, "WIFI GOT IP", 7000);
	  if(Err_WIFI_NONE){
			printf("Linked route successfully\r\n");
		}else{
			printf("Unlink route,errcode(%d)\r\n",ret);
		}	

//    sprintf(cmd, "AT+CWJAP=\"TCP\",\"%s\",\"%s\"\r\n", ssid, pwd);	
//	  app_atkmodule_printf(cmd);
//	  stkdly_s(5);
	  
	  if(True == g_atkmodule_rxtkn_ovr)
		{
			printf("In joinAP,rec{%s}\r\n",g_atkmodule_rxbuff);
			app_atkmodule_uartrx_rst();
		}
	  
    if (ret == Err_WIFI_NONE)
    {
        return Err_WIFI_NONE;
    }
    else
    {
        return Err_WIFI_ERROR;
    }
}

/**
 * @brief       ATK-MW8266D获取IP地址
 * @param       buf: IP地址，需要16字节内存空间
 * @retval      Err_WIFI_NONE  : 获取IP地址成功
 *              Err_WIFI_ERROR: 获取IP地址失败
 */
uint8_t app_esp_get_ip(char *buf)
{
    uint8_t ret;
    char *p_start;
    char *p_end;
    
    ret = app_esp_send_at_cmd("AT+CIFSR", "OK", 500);
    if (ret != Err_WIFI_NONE)
    {
        return Err_WIFI_ERROR;
    }
    
    p_start = strstr((const char *)app_atkmodule_get_uartrx_frame(), "\"");
    p_end = strstr(p_start + 1, "\"");
    *p_end = '\0';
    sprintf(buf, "%s", p_start + 1);
    
    return Err_WIFI_NONE;
}

/**
 * @brief       ATK-MW8266D连接TCP服务器
 * @param       server_ip  : TCP服务器IP地址
 *              server_port: TCP服务器端口号
 * @retval      Err_WIFI_NONE  : 连接TCP服务器成功
 *              Err_WIFI_ERROR: 连接TCP服务器失败
 */
uint8_t app_esp_connect_tcp_server(char *server_ip, char *server_port)
{
    uint8_t ret;
    char cmd[64];
    
    sprintf(cmd, "AT+CIPSTART=\"TCP\",\"%s\",%s", server_ip, server_port);
    ret = app_esp_send_at_cmd(cmd, "CONNECT", 5000);
    if (ret == Err_WIFI_NONE)
    {
        return Err_WIFI_NONE;
    }
    else
    {
        return Err_WIFI_ERROR;
    }
}

/**
 * @brief       ATK-MW8266D进入透传
 * @param       无
 * @retval      Err_WIFI_NONE  : 进入透传成功
 *              Err_WIFI_ERROR: 进入透传失败
 */
uint8_t app_esp_enter_serialnet(void)
{
    uint8_t ret;
    
    ret  = app_esp_send_at_cmd("AT+CIPMODE=1", "OK", 500);
    ret += app_esp_send_at_cmd("AT+CIPSEND", ">", 500);
    if (ret == Err_WIFI_NONE)
    {
        return Err_WIFI_NONE;
    }
    else
    {
        return Err_WIFI_ERROR;
    }
}

/**
 * @brief       ATK-MW8266D退出透传
 * @param       无
 * @retval      无
 */
void app_esp_exit_serialnet(void)
{
    app_atkmodule_printf("+++");
}

/**
 * @brief       ATK-MW8266D连接原子云服务器
 * @param       id : 原子云设备编号
 *              pwd: 原子云设备密码
 * @retval      Err_WIFI_NONE  : 连接原子云服务器成功
 *              Err_WIFI_ERROR: 连接原子云服务器失败
 */
uint8_t app_esp_connect_atkcld(char *id, char *pwd)
{
    uint8_t ret;
    char cmd[64];
    
    sprintf(cmd, "AT+ATKCLDSTA=\"%s\",\"%s\"", id, pwd);
    ret = app_esp_send_at_cmd(cmd, "CLOUD CONNECTED", 10000);
    if (ret == Err_WIFI_NONE)
    {
        return Err_WIFI_NONE;
    }
    else
    {
        return Err_WIFI_ERROR;
    }
}

/**
 * @brief       ATK-MW8266D断开原子云服务器连接
 * @param       无
 * @retval      Err_WIFI_NONE  : 断开原子云服务器连接成功
 *              Err_WIFI_ERROR: 断开原子云服务器连接失败
 */
uint8_t app_esp_disconnect_atkcld(void)
{
    uint8_t ret;
    
    ret = app_esp_send_at_cmd("AT+ATKCLDCLS", "CLOUD DISCONNECT", 500);
    if (ret == Err_WIFI_NONE)
    {
        return Err_WIFI_NONE;
    }
    else
    {
        return Err_WIFI_ERROR;
    }
}

//--end atk-codes--------------------------------------------------------------------end----

///====BSP-BTBLE==========================================================================================
/********************************************************
 * @brief  (validated)bsp-init for ESP-devs
 * @param       buadrate: ATK-MODULE UART通讯波特率
 * @retval      Err_WIFI_NONE  : ATK-MODULE初始化成功
 *              Err_WIFI_ERROR: ATK-MODULE初始化失败
 ********************************************************/
void bsp_esp_devs_init(void)
{
	 app_esp_exit_deepsleep() ;	
   stkdly_ms(__DlyMs_Esp);
	
	 app_esp_exit_lowpower() ;
   stkdly_ms(__DlyMs_Esp);
	
 	 app_esp_check_wkmd();
	 stkdly_ms(__DlyMs_Esp);
	
	 app_esp_set_powermode(CHECK_CMD_WIFI) ; 
   stkdly_ms(__DlyMs_Esp);
	
   app_esp_setwkmd_dualslv_sppble(); //set workmode to dual-slave(spp&ble)
   stkdly_ms(__DlyMs_Esp);
	
	 app_esp_check_powermode() ;
   stkdly_ms(__DlyMs_Esp); 
	
	 app_esp_disconnect();
	 stkdly_ms(__DlyMs_Esp); 
	
   app_atkmodule_uartrx_polltst();
	 app_handle_espdevsta_poll(g_atkmodule_rxbuff, &g_atkmoudle_esp_dev0);
}

/***************************************************
 * @brief  (validated) 
 * @param  void
 * @retval void
 ***************************************************/
uint8_t task_esp_rxmsg_poll(void)
{	
	static emWIFI_DevState_t ret = WIFI_Disconnect;
  static uint8_t *buf = g_atkmodule_rxbuff;
  static sttWIFI_DevParas_t* tmpdev = &g_atkmoudle_esp_dev0;	

  app_handle_espdevsta_poll(buf, tmpdev); // get ESP dev sta_dev
  if(True == g_atkmodule_rxtkn_ovr)
	{
		switch(tmpdev->sta_dev)
		{
			case WIFI_Connect:
				buf = g_atkmodule_rxbuff;
				printf("TTconn-RxMsg:{%s}\r\n",buf);  
				break;
			
			case WIFI_Ready:
			case WIFI_Disconnect:

			  buf = app_atkmodule_get_uartrx_frame();
				printf("Disconn-RxMsg:{%s}\r\n",buf);  
				break;			
			
			default : break;
		}			
		
		app_atkmodule_uartrx_rst(); 
  }
	return ret;
}

/*******************************************************************
 * @brief (validated) tx message handle-poll
           1 WIFI_Connect:	TTconnection,tx msg from dbcom	
			     2 WIFI_Ready or WIFI_Disconnect: AT cmds from dbcom
 * @param  void
 * @notice 
        -1-, dbcom rx dose not save "\r\n",usr must add it
 * @retval 
 ***************************************
 printf("ATcmd:%s; dbcom-rxlen = %d\r\n",cmd,g_dbcom_rx_curcnt);
 *******************************************************************/
uint8_t task_esp_txmsg_poll(void)
{	
	static emWIFI_DevState_t ret = WIFI_Disconnect;
  static uint8_t *buf = g_atkmodule_rxbuff;
  static sttWIFI_DevParas_t* tmpdev = &g_atkmoudle_esp_dev0;	

  app_handle_espdevsta_poll(buf, tmpdev);

  if(True == g_dbcom_rxtkn_ovr)
	{
		switch(tmpdev->sta_dev)
		{
			case WIFI_Connect:	 // TTconnection,tx msg from dbcom	
				app_atkmodule_printf((char*)g_dbcom_rxbuff);
				break;			
				
			case WIFI_Ready:
			case WIFI_Disconnect: //AT cmds from dbcom
				if(NULL == strncmp((sc8_t*)g_dbcom_rxbuff,"AT+",3)) 
				{
					char cmd[12] = {0};
					sprintf(cmd,"%s\r\n",(char*)g_dbcom_rxbuff);
				  printf("ATcmd:%s; dbcom-rxlen = %d\r\n",cmd,g_dbcom_rx_curcnt);
			    app_atkmodule_printf((char*)cmd);
					app_dbcom_rst(); 
          stkdly_ms(__DlyMs_Esp);
				}
        break;
			
			default : break;
		}			
	
    app_dbcom_rst(); 
  }//< if(True == g_dbcom_rxtkn_ovr)>
	
	return ret;
}


///====End BSP-BTBLE===============================================================================End====


////====Codes-ESP=========================================================================================
///--ESP-devs setting------------------------------------------------------------------------------
/*********************************************************************************
 * @brief  (validated) Set workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  mode : work mode
								0       |     01    |     02    |        03       |     04     |
				 ---------------|-----------|-----------|-----------------|------------|
				 check workmode | BLE-Slave | SPP-Slave | slave BLE & SPP | BLE-CWMODE |

 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
 *********************************************************************************/
static uint8_t __esp_set_workmode(uint8_t mode)
{
    uint8_t ret;
		
    switch(mode)
		{
			case 0:
        app_atkmodule_printf("AT+CWMODE\r\n");  // app_free_printf(&g_atkmodule_hdr, "AT+CWMODE\r\n", cmd);		
			  stkdly_ms(__DlyMs_Esp);
        ret = app_atkmodule_uartrx_polltst();
			  break;
			
			case 1:
			  ret = app_atkmodule_send_at_cmd("AT+CWMODE=1", "OK", 500); //Enable BLE-Slave
			  break;
			
			case 2:
			  ret = app_atkmodule_send_at_cmd("AT+CWMODE=2", "OK", 500); // Enable SPP-Slave
			  break;
			
			case 3:
			  ret = app_atkmodule_send_at_cmd("AT+CWMODE=3", "OK", 500); // Enable double slave, BLE & SPP 
			  break;	

//			case 4:
//			  ret = app_atkmodule_send_at_cmd("AT+CWMODE=04", "OK", 1000); // Enable BLE-CWMODE
//			  break;		
			
			default: break;
		}
		
    if (ret != Err_WIFI_NONE)
    {
        return Err_WIFI_ERROR;
    }
    
    return Err_WIFI_NONE;
}


/*********************************************************************************
 * @brief  (validated) Set ble-slave workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval void
 *********************************************************************************/
uint8_t app_esp_setwkmd_bleslv(void)
{
	uint8_t ret = __esp_set_workmode(0x1);
	return ret;
}

/*********************************************************************************
 * @brief  (validated) Set ble-CWMODE workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
 *********************************************************************************/
uint8_t app_esp_setwkmd_blemtr(void)
{
	uint8_t ret = __esp_set_workmode(0x4);
	return ret;
}

/*********************************************************************************
 * @brief  (validated) Set SPP-Slave workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
 *********************************************************************************/
uint8_t app_esp_setwkmd_sppslv(void)
{
	uint8_t ret = __esp_set_workmode(0x2);
	return ret;
}

/*********************************************************************************
 * @brief  (validated) Set SPP-BLE-Slave double workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
 *********************************************************************************/
uint8_t app_esp_setwkmd_dualslv_sppble(void)
{
	uint8_t ret = __esp_set_workmode(0x3);
	return ret;
}

/*********************************************************************************
 * @brief  (validated) Check workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval void
 *********************************************************************************/
uint8_t app_esp_check_wkmd(void)
{
	uint8_t ret = __esp_set_workmode(0x00);
	return ret;
}

/**
 * @brief       设置ATK-MODULE b-type name
 * @param       name: 蓝牙名称
                  NULL,check namb
                  others,b-type name
 * @retval      Err_WIFI_NONE  : 设置ATK-MODULE蓝牙名称成功
 *              Err_WIFI_ERROR: 设置ATK-MODULE蓝牙名称失败
 */
uint8_t app_esp_set_name(char *name)
{
    uint8_t ret;
    char cmd[64];

    if(name == NULL){
			app_atkmodule_printf("AT+NAME\r\n")		;
		  stkdly_ms(__DlyMs_Esp);
			ret = app_atkmodule_uartrx_polltst();
			
		}else{			
			sprintf(cmd, "AT+NAME=%s", name);
			ret = app_atkmodule_send_at_cmd(cmd, "OK", 100);
		}	

    if (ret != Err_WIFI_NONE)
    {
        return Err_WIFI_ERROR;
    }
    
    return Err_WIFI_NONE;
}


/**
 * @brief       设置ATK-MODULE b-type name
 * @param       name: 蓝牙名称
                  NULL,check namb
                  others,b-type name
 * @retval      Err_WIFI_NONE  : 设置ATK-MODULE蓝牙名称成功
 *              Err_WIFI_ERROR: 设置ATK-MODULE蓝牙名称失败
 */
uint8_t app_esp_set_namb(char *name)
{
    uint8_t ret;
    char cmd[64];

    if(name == NULL){
			app_atkmodule_printf("AT+NAMB\r\n")		;
			stkdly_ms(__DlyMs_Esp);
			ret = app_atkmodule_uartrx_polltst();
			
		}else{			
			sprintf(cmd, "AT+NAMB=%s", name);
			ret = app_atkmodule_send_at_cmd(cmd, "OK", 100);
		}	

    if (ret != Err_WIFI_NONE)
    {
        return Err_WIFI_ERROR;
    }
    
    return Err_WIFI_NONE;
}

/*********************************************************************************
 * @brief  (validated) Set powermode and check it for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  dptm,
             0,Auto enter lowpower mode
             1, normal power mode
             others,Err_WIFI_INVAL
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
           Err_WIFI_INVAL , error 
 ******************************************************************			
	    case WIFI_PwrMd_CHK     :  // check power mode
					app_atkmodule_printf("AT+PWRM\r\n");  
					stkdly_us(100);
					if(True == g_atkmodule_rxtkn_ovr)
					{
             if(NULL != strstr((sc8_t*)g_atkmodule_rxbuff,"+PWRM=0")){
							 g_atkmoudle_esp_dev0.sta_dev = WIFI_LowPower;
						 }
						 app_atkmodule_uartrx_rst();
					}						
          break;	
 *********************************************************************************/
uint8_t app_esp_set_powermode(emWIFI_PwrMd_t pwr) 
{
    uint8_t ret;
    char cmd[16];
    assert_param(IS_VALID_PWRMD_ESP(pwr)	);
	
    switch(pwr)
		{
      case WIFI_PwrMd_AutoLow :  // enable lowpower mode
					sprintf(cmd, "AT+PWRM=%d",pwr); 
					ret = app_atkmodule_send_at_cmd(cmd, "OK", 100);				 
          break;			
			
      case WIFI_PwrMd_Normal  :  // enable normal power mode
					sprintf(cmd, "AT+PWRM=%d",pwr); 
					ret = app_atkmodule_send_at_cmd(cmd, "OK", 100);				 				
          break;					

			
      default	:
				  ret = Err_WIFI_INVAL;
          break;					
		}			

    
    return ret;
}

/*******************************************************************
 * @brief       Set RF-power grade for LM`s bluetooth&ble dev 
                using serialport(UART/USART)-interface
                LM(www.lbluetooth.com)
 * @param       pwr, enum RF-power grade
                    check it in res_spBTBLE.h
 * @retval      Err_WIFI_NONE  : 
 *              Err_WIFI_ERROR:
 *************************************************************/
uint8_t app_esp_set_rfpower(emWIFI_PwrGrd_t pwr)
{
    uint8_t ret;
    char cmd[16];
		
		if(CHECK_CMD_WIFI == pwr){
			app_atkmodule_printf("AT+POWE\r\n");
			stkdly_ms(4);
			ret = app_atkmodule_uartrx_polltst();			
			
		}else{
			assert_param(IS_VALID_PWRGRD_ESP(pwr));
			sprintf(cmd, "AT+POWE=%d", pwr); // Esp8266,
			ret = app_atkmodule_send_at_cmd(cmd, "OK", 100);			
		}

    if (ret != Err_WIFI_NONE)
    {
        return Err_WIFI_ERROR;
    }
    
    return Err_WIFI_NONE;
}

/*********************************************************************************
 * @brief  Set time entering lowpower for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  tm,time after that enter lowpower
             0,error
             others,enter lowpower after dptm s
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
  
 *********************************************************************************/
uint8_t app_esp_settime_intolowpower( uint8_t tm) 
{
    uint8_t ret;
    char cmd[16];
	  
	  if(tm == 0){
			ret = Err_WIFI_INVAL;
			
		}else{
			sprintf(cmd, "AT+AST=%d",tm);   // enter normal power mode 
			ret = app_atkmodule_send_at_cmd(cmd, "OK", 100);	
		}

    return ret;	
}
///--end ESP-devs setting-------------------------------------------------------------------end----

///---ESP-devs handle------------------------------------------------------------------------------

/*********************************************************************************
 * @brief   Disconnect LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
 *********************************************************************************/
uint8_t app_esp_disconnect(void) 
{
    uint8_t ret;
    char cmd[16];

		sprintf(cmd, "AT+DSCET=1"); 
		ret = app_atkmodule_send_at_cmd(cmd, "OK", 100);			

    if (ret != Err_WIFI_NONE)
    {
        return Err_WIFI_ERROR;
    }
    
    return Err_WIFI_NONE;
}


/*********************************************************************************
 * @brief  (validated) Check powermode  for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *        
 *********************************************************************************/
uint8_t app_esp_check_powermode(void) 
{
    uint8_t ret = Err_WIFI_NONE;
    char cmd[16];
	
    ret = app_esp_check_wkmd();
   	stkdly_ms(__DlyMs_Esp);
	  app_atkmodule_uartrx_rst();
		app_atkmodule_printf("AT+PWRM\r\n");  
		stkdly_ms(__DlyMs_Esp);
    
		if(True == g_atkmodule_rxtkn_ovr)
		{  
			
			 //Auto entering lowpower mode
			 if(NULL != strstr((sc8_t*)g_atkmodule_rxbuff,"\r\n+PWRM=0")){
				 g_atkmoudle_esp_dev0.sta_dev = WIFI_LowPower;
			   printf("PwrMd-->AutoEnter Lowpower>>\r\n");
				 
				//Normal power mode 
			 }else if(NULL != strstr((sc8_t*)g_atkmodule_rxbuff,"\r\n+PWRM=1")){
				 g_atkmoudle_esp_dev0.sta_dev = WIFI_Normal;
				 printf("PwrMd-->Enter Normalpower>>\r\n");
			 }
			 app_atkmodule_uartrx_rst();
		}						
   
    return ret;
}


/*********************************************************************************
 * @brief  (validated)Exit lowpower mode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
  
 *********************************************************************************/
uint8_t app_esp_exit_lowpower(void) 
{
    uint8_t ret;
    char cmd[16];
	
		app_atkmodule_printf("AT+ADVDATA\r\n"); //查询广播内容
    stkdly_ms(__DlyMs_Esp);  
		ret = app_atkmodule_uartrx_polltst();	
	
		sprintf(cmd, "AT+PWRM=1");   // enter normal power mode 
		ret = app_atkmodule_send_at_cmd(cmd, "OK", 100);
    stkdly_ms(__DlyMs_Esp);  	
    printf("BTBLE has exit from lowpower-mode\r\n\r\n");
	
    if (ret != Err_WIFI_NONE)
    {
        return Err_WIFI_ERROR;
    }
    return Err_WIFI_NONE;
}


/*********************************************************************************
 * @brief   Enter deepsleep and check dptim for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  dptm,time to enter deepsleep
             0,error
             0xcf,=CHECK_CMD_WIFI,check how many seconds to enter deep sleep
             others(IS_VALID_DEEPSLP_ESP) ,enter deepsleep after dptm s
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
  
 *********************************************************************************/
uint8_t app_esp_enter_deepsleep( uint8_t dptm) 
{
    uint8_t ret;
    char cmd[16];
	  		
		if(dptm < WIFI_DeepSleep_Min){
		  printf("Error para,at line%d-<file:%s>,<func:%s>!!!!  \r\n", \
			                      __LINE__,__FILE__,__FUNCTION__);
			return Err_WIFI_INVAL;
			
		}else if(IS_VALID_DEEPSLP_ESP(dptm)){
			
			sprintf(cmd, "AT+AUST=%d",dptm); 
			ret = app_atkmodule_send_at_cmd(cmd, "OK", 70);
			if(ret == Err_WIFI_TIMEOUT){
				 ret = Err_WIFI_ERROR;
				
			}else{		
					printf("BTBLE will enter deepsleep after %d s\r\n",dptm);	
					stkdly_s((uint8_t)dptm);
					g_atkmoudle_esp_dev0.sta_dev = WIFI_DeepSleep;
					printf("BTBLE entered deepsleep.\r\n");	   				
			}
			
		}else if(dptm == CHECK_CMD_WIFI){
			app_atkmodule_printf("AT+AUST\r\n");  
			stkdly_ms(__DlyMs_Esp);
			ret = app_atkmodule_uartrx_polltst();					
		}

    if (ret != Err_WIFI_NONE)
    {
        return Err_WIFI_ERROR;
    }
    
    return Err_WIFI_NONE;
}

/*********************************************************************************
 * @brief  (validated)Exit deepsleep for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
 *******************************************************************************
  g_atkmoudle_esp_dev0.sta_dev ,app_atkmodule_get_uartrx_frame
 *********************************************************************************/
uint8_t app_esp_exit_deepsleep(void) 
{
    uint8_t ret;
    char cmd[16];
	
		app_atkmodule_printf("AT+CWMODE\r\n");  //check name on daul-workmode 
    stkdly_ms(__DlyMs_Esp); 
		ret = app_atkmodule_uartrx_polltst();	
	
		sprintf(cmd, "AT+AUST=0"); 
		ret = app_atkmodule_send_at_cmd(cmd, "OK", 100);
	  stkdly_ms(__DlyMs_Esp); 
    printf("BTBLE has exit from deepsleep\r\n\r\n");
	
    if (ret != Err_WIFI_NONE)
    {
        return Err_WIFI_ERROR;
    }
    
    return Err_WIFI_NONE;
}

/****************************************************************
 * @brief  (validated)Reset the wifi-dev using software codes
 * @param       void
 * @retval      Err_WIFI_NONE  : 设置ATK-MODULE蓝牙名称成功
 *              Err_WIFI_ERROR: 设置ATK-MODULE蓝牙名称失败
 **************************************************************/
uint8_t app_esp_dev_sftrst(void)
{
    uint8_t ret;
    char cmd[64];

		sprintf(cmd, "AT+RST");
		ret = app_atkmodule_send_at_cmd(cmd, "OK", 100);
	
    if (ret != Err_WIFI_NONE)
    {
        return Err_WIFI_ERROR;
    }
    
    return Err_WIFI_NONE;
}

/***************************************************
 * @brief  Poll, handle ESP dev`s sta_dev polly
           validated 
 * @param  void
 * @notice 
        -1-, must disable app_atkmodule_uartrx_polltst()
             
 * @retval invalid value
 *******************************************
 app_atkmodule_uartrx_rst();
 ***************************************************/
uint8_t app_handle_espdevsta_poll(uint8_t* buf,sttWIFI_DevParas_t* dev)
{	
	static uint8_t ret = 0;
	
	if((WIFI_Connect != dev->sta_dev ) && \
		 (NULL != strstr((const char *)buf, "IM_CONN"))) 
	{
			dev->sta_dev = WIFI_Connect;
			printf("LmbtDev is connected\r\n\r\n");
		
	}
	else if ((WIFI_Ready != dev->sta_dev )  && \
					 (NULL != strstr((const char *)buf, "IM_READY")))
	{
			dev->sta_dev = WIFI_Ready;		
			printf("LmbtDev is ready\r\n\r\n");
		
	}
	else if ((WIFI_Disconnect != dev->sta_dev )  &&  \
					 (NULL != strstr((const char *)buf, "IM_DISC")) )
	{
			dev->sta_dev = WIFI_Disconnect;
			printf("LmbtDev is disconnected\r\n\r\n");		
	}	

	return ret;
}

///--end ESP-devs handle--------------------------------------------------------------------end----


///--ESP-devs uart---------------------------------------------------------------------------------

/**************************************************************
 * @brief       (validated)设置ATK-MODULE串口参数
 * @param       save    : 是否保存即将设置的数据
                        True,将设置参数写入esp的flash
                        False，不保存设置参数
                baudrate: 波特率
 *              data    : 数据位
 *              pari    : 校验位
 *              stop    : 停止位
                flow ,   hardflow
 * @retval      Err_WIFI_NONE   : 设置ATK-MODULE串口参数成功
 *              Err_WIFI_ERROR : 设置ATK-MODULE串口参数失败
 *              Err_WIFI_INVAL: 函数参数错误
 **************************************************
ret = app_atkmodule_uartrx_polltst()
 ***************************************************************/
uint8_t app_esp_config_uart( Bool                  save,     \
                             emEspUart_baud_t      baudrate, \
                             emEspUart_databits_t  data,     \
                             emEspUart_stop_t      stop,     											
                             emEspUart_pari_t      pari,     \
                             emEspUart_hardflow_t  flow    
                          )
{
    uint8_t ret;
    char cmd[24];	
    assert_param(IS_VALID_UART_BAUDRATE_ESP(baudrate));	
    assert_param(IS_VALID_UART_BITS_ESP(data));	
    assert_param(IS_VALID_UART_STOP_ESP(stop));		
    assert_param(IS_VALID_UART_PARI_ESP(pari)); 			
    assert_param(IS_VALID_UART_FLOW_ESP(flow));	

	  
	  if(True == save){
      sprintf(cmd,"AT+UART_DEF=%d,%d,%d,%d,%d\r\n",baudrate,data,stop,pari,flow);  	
		}else {
      sprintf(cmd,"AT+UART_CUR=%d,%d,%d,%d,%d\r\n",baudrate,data,stop,pari,flow);  	
		}
    app_atkmodule_printf(cmd);		

    return Err_WIFI_NONE;
}


/*********************************************************************************
 * @brief  (validated)Poll-proccess for UART/USART rx of LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           used to test atkmodule_uartrx in intterupt  
 * @param  void
 * @retval void
 *********************************************************************************/
uint8_t app_atkmodule_uartrx_polltst()
{
	  static uint8_t ret = 0;

    if(True == g_atkmodule_rxtkn_ovr){
		   printf("Rec:<%s>\r\n",g_atkmodule_rxbuff);
		   app_atkmodule_uartrx_rst();		
       ret = 	Err_WIFI_NONE ;		
		}else{
       ret = 	Err_WIFI_ERROR  ;					 
		}
		
		return ret;
} //<void app_atkmodule_uartrx_polltst()>

///--end ESP-devs uart----------------------------------------------------------------------end----

///====End Codes-ESP==============================================================================End====



/*----Endline : Full file--------------------------------------------------------------------------All-End---*/


