/******************************************************************************************************
 * @file        ESP.h
 * @author      Edwoy
 * @version     V1.0
 * @date        2021-10-27
 * @brief       Bluetooth&BLE drive h of serialport communication
 * @license     Copyright (c) 2020-2032
 ****************************************************************************************************
 * @attention
 ****************************************************************************************************
 * @note
 *    1 Default hard
          platform: ATK-DMF407
          module : Esp8266 of LM(www.lbluetooth.com)			
 ****************************************************************************************************
 * @update
 *   V1.0 20211027 the orgn version from ATK-DMF407
 *
 ****************************************************************************************************
 */

#ifndef _CPT_WIFI_H_
#define _CPT_WIFI_H_

#include "ThisProj_Glb.h"
#include SYS_HEAD
#include UART_HEAD
#include RES_WIFI_HEAD   //"./component/spWiFi/ESP/res_esp_uart.h"
#include UTY_WIFI_HEAD  //"./component/spWiFi/UTY/utyBtBle.h"

//--atk-codes-------------------------------------------------------------------------------
/**
 * @brief       ATK-MW8266D硬件初始化
 * @param       无
 * @retval      无
 */
static void app_esp_rstgpio_init(void);

/**
 * @brief       设置ATK-MW8266D工作模式
 * @param       mode: 1，Station模式
 *                    2，AP模式
 *                    3，AP+Station模式
 * @retval      Err_WIFI_NONE   : 工作模式设置成功
 *              Err_WIFI_ERROR : 工作模式设置失败
 *              Err_WIFI_INVAL: mode参数错误，工作模式设置失败
 */
uint8_t app_esp_set_mode(uint8_t mode);

/**
 * @brief       ATK-MW8266D硬件复位
 * @param       无
 * @retval      无
 */
void app_esp_dev_hdrst(void);

/**
 * @brief       ATK-MW8266D初始化
 * @param       baudrate: ATK-MW8266D UART通讯波特率
 * @retval      Err_WIFI_NONE  : ATK-MW8266D初始化成功，函数执行成功
 *              Err_WIFI_ERROR: ATK-MW8266D初始化失败，函数执行失败
 */
uint8_t app_esp_init(uint32_t baudrate);
/**
 * @brief       ATK-MW8266D恢复出厂设置
 * @param       无
 * @retval      Err_WIFI_NONE  : 恢复出场设置成功
 *              Err_WIFI_ERROR: 恢复出场设置失败
 */
uint8_t app_esp_restore(void);

/**
 * @brief       ATK-MW8266D设置回显模式
 * @param       cfg: 0，关闭回显
 *                   1，打开回显
 * @retval      Err_WIFI_NONE  : 设置回显模式成功
 *              Err_WIFI_ERROR: 设置回显模式失败
 */
uint8_t app_esp_ate_config(uint8_t cfg);
/**
 * @brief       ATK-MW8266D连接WIFI
 * @param       ssid: WIFI名称
 *              pwd : WIFI密码
 * @retval      Err_WIFI_NONE  : WIFI连接成功
 *              Err_WIFI_ERROR: WIFI连接失败
 */
uint8_t app_esp_link_ap(char *ssid, char *pwd);

/**
 * @brief       ATK-MW8266D获取IP地址
 * @param       buf: IP地址，需要16字节内存空间
 * @retval      Err_WIFI_NONE  : 获取IP地址成功
 *              Err_WIFI_ERROR: 获取IP地址失败
 */
uint8_t app_esp_get_ip(char *buf);

/**
 * @brief       ATK-MW8266D连接TCP服务器
 * @param       server_ip  : TCP服务器IP地址
 *              server_port: TCP服务器端口号
 * @retval      Err_WIFI_NONE  : 连接TCP服务器成功
 *              Err_WIFI_ERROR: 连接TCP服务器失败
 */
uint8_t app_esp_connect_tcp_server(char *server_ip, char *server_port);

/**
 * @brief       ATK-MW8266D进入透传
 * @param       无
 * @retval      Err_WIFI_NONE  : 进入透传成功
 *              Err_WIFI_ERROR: 进入透传失败
 */
uint8_t app_esp_enter_serialnet(void);

/**
 * @brief       ATK-MW8266D退出透传
 * @param       无
 * @retval      无
 */
void app_esp_exit_serialnet(void);

/**
 * @brief       ATK-MW8266D连接原子云服务器
 * @param       id : 原子云设备编号
 *              pwd: 原子云设备密码
 * @retval      Err_WIFI_NONE  : 连接原子云服务器成功
 *              Err_WIFI_ERROR: 连接原子云服务器失败
 */
uint8_t app_esp_connect_atkcld(char *id, char *pwd);
/**
 * @brief       ATK-MW8266D断开原子云服务器连接
 */
uint8_t app_esp_disconnect_atkcld(void);
//--end atk-codes--------------------------------------------------------------------end----

///====Codes-ESP=========================================================================================
	
/**
 * @brief   handle , interrupt mode
            validated 
 * @note  
       -1-, used at etf_tsk_sysrun4() in project.c   
 * @retval  无
 */
uint8_t app_handle_espdevsta_poll(uint8_t* ,sttWIFI_DevParas_t* );

/*********************************************
 * @brief       ATK-MODULE AT test
 * @param       无
 * @retval      Err_WIFI_NONE     : success
 *              Err_WIFI_TIMEOUT: error
 *********************************************/
uint8_t app_esp_at_test(void);

/*********************************************************************************
 * @brief  Check workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @notice 
           -1-,Must base on usart.h/c generated by cbx
 * @retval void
 *********************************************************************************/
//void app_esp_init(void) ;

/*********************************************************************************
 * @brief  Check workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval void
 *********************************************************************************/
uint8_t app_esp_check_wkmd(void);

/*********************************************************************************
 * @brief  Set ble-slave workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval void
 *********************************************************************************/
uint8_t app_esp_setwkmd_bleslv(void);

/*********************************************************************************
 * @brief  Set ble-master workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
 *********************************************************************************/
uint8_t app_esp_setwkmd_blemtr(void);

/*******************************************************************
 * @brief       Set RF-power grade for LM`s bluetooth&ble dev 
                using serialport(UART/USART)-interface
                LM(www.lbluetooth.com)
 * @param       pwr, enum RF-power grade
                    check it in res_spBTBLE.h
 * @retval      Err_WIFI_NONE  : 
 *              Err_WIFI_ERROR:
 *************************************************************/
uint8_t app_esp_set_rfpower(emWIFI_PwrGrd_t pwr);

/*******************************************************************
 * @brief       Set uart`s baudrate for LM`s bluetooth&ble dev 
                using serialport(UART/USART)-interface
                LM(www.lbluetooth.com)
 * @param       baudrate, checked emEspUart_baud_t 
                in res_spBTBLE.h
 * @retval      Err_WIFI_NONE  : 
 *              Err_WIFI_ERROR: 
 ******************************************************************/
uint8_t app_esp_set_uart_baud(emEspUart_baud_t  baudrate);

/*******************************************************************
 * @brief       Set uart`s baudrate for LM`s bluetooth&ble dev 
                using serialport(UART/USART)-interface
                LM(www.lbluetooth.com)
 * @param       baudrate, checked emEspUart_baud_t 
                in res_spBTBLE.h
 * @retval      Err_WIFI_NONE  : ATK-MODULE进入配置模式成功
 *              Err_WIFI_ERROR: ATK-MODULE进入配置模式失败
 ******************************************************************/
uint8_t app_esp_set_uart_stop(emEspUart_stop_t stop);

/*******************************************************************
 * @brief       设置ATK-MODULE串口参数
 * @param       baudrate: 波特率
 *              data    : 数据位
 *              pari    : 校验位
 *              stop    : 停止位
 * @retval      Err_WIFI_NONE   : 设置ATK-MODULE串口参数成功
 *              Err_WIFI_ERROR : 设置ATK-MODULE串口参数失败
 *              Err_WIFI_INVAL: 函数参数错误
                           emEspUart_pari_t     pari,     \
                           emEspUart_stop_t     stop
 ******************************************************************/
uint8_t app_esp_set_uart_flow(emEspUart_stop_t flow);


/*******************************************************************
 * @brief       设置ATK-MODULE串口参数
 * @param       baudrate: 波特率
 *              data    : 数据位
 *              pari    : 校验位
 *              stop    : 停止位
 * @retval      Err_WIFI_NONE   : 设置ATK-MODULE串口参数成功
 *              Err_WIFI_ERROR : 设置ATK-MODULE串口参数失败
 *              Err_WIFI_INVAL: 函数参数错误
                           emEspUart_pari_t     pari,     \
                           emEspUart_stop_t     stop
 ******************************************************************/
uint8_t app_esp_set_uart_parity(emEspUart_stop_t pari);

/*********************************************************************************
 * @brief  Set SPP-Slave workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
 *********************************************************************************/
uint8_t app_esp_setwkmd_sppslv(void);

/*********************************************************************************
 * @brief  Set SPP-BLE-Slave double workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
 *********************************************************************************/
uint8_t app_esp_setwkmd_dualslv_sppble(void);

/*********************************************************************************
 * @brief   Disconnect LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
 *********************************************************************************/
uint8_t app_esp_disconnect(void) ;

/*********************************************************************************
 * @brief   Check powermode  for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *        
 *********************************************************************************/
uint8_t app_esp_check_powermode(void) ;
	
/*********************************************************************************
 * @brief   Set powermode and check it for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  dptm,
             0,Auto enter lowpower mode
             1, normal power mode
             0xcf,=CHECK_CMD_WIFI,check 
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
  
 *********************************************************************************/
uint8_t app_esp_set_powermode(emWIFI_PwrMd_t pwr) ;

/*********************************************************************************
 * @brief  Exit lowpower mode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
  
 *********************************************************************************/
uint8_t app_esp_exit_lowpower(void) ;

/*********************************************************************************
 * @brief  Set time entering lowpower for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  tm,time after that enter lowpower
             0,error
             others,enter lowpower after dptm s
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
  
 *********************************************************************************/
uint8_t app_esp_settime_intolowpower( uint8_t tm) ;

/*********************************************************************************
 * @brief   Enter deepsleep and check dptim for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  dptm,time to enter deepsleep
             0,error
             0xcf,=CHECK_CMD_WIFI,check 
             others(IS_VALID_DEEPSLP_ESP) ,time to enter deepsleep
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
  
 *********************************************************************************/
uint8_t app_esp_enter_deepsleep( uint8_t dptm) ;

/*********************************************************************************
 * @brief  Exit deepsleep for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_WIFI_NONE  : success
 *         Err_WIFI_ERROR: error
  
 *********************************************************************************/
uint8_t app_esp_exit_deepsleep(void) ;

/**
 * @brief       设置ATK-MODULE b-type name
 * @param       name: 蓝牙名称
                  NULL,check namb
                  others,b-type name
 * @retval      Err_WIFI_NONE  : 设置ATK-MODULE蓝牙名称成功
 *              Err_WIFI_ERROR: 设置ATK-MODULE蓝牙名称失败
 */
uint8_t app_esp_set_name(char *name);


/**
 * @brief       设置ATK-MODULE b-type name
 * @param       name: 蓝牙名称
                  NULL,check namb
                  others,b-type name
 * @retval      Err_WIFI_NONE  : 设置ATK-MODULE蓝牙名称成功
 *              Err_WIFI_ERROR: 设置ATK-MODULE蓝牙名称失败
 */
uint8_t app_esp_set_namb(char *name);

/**************************************************************
 * @brief       设置ATK-MODULE串口参数
 * @param       baudrate: 波特率
 *              data    : 数据位
 *              pari    : 校验位
 *              stop    : 停止位
                flow ,   hardflow
 * @retval      Err_WIFI_NONE   : 设置ATK-MODULE串口参数成功
 *              Err_WIFI_ERROR : 设置ATK-MODULE串口参数失败
 *              Err_WIFI_INVAL: 函数参数错误
 ***************************************************************/
uint8_t app_esp_config_uart( Bool                  save,     \
                             emEspUart_baud_t      baudrate, \
                             emEspUart_databits_t  bits,     \
                             emEspUart_stop_t      stop,     											
                             emEspUart_pari_t      pari,     \
                             emEspUart_hardflow_t  flow    
                          );

/****************************************************************
 * @brief       Reset the ESP wifi-dev
 * @param       void
 * @retval      Err_WIFI_NONE  : 设置ATK-MODULE蓝牙名称成功
 *              Err_WIFI_ERROR: 设置ATK-MODULE蓝牙名称失败
 **************************************************************/
uint8_t app_esp_dev_sftrst(void);

/*********************************************************************************
 * @brief  Poll-proccess for UART/USART rx of LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param   rxframe,
                exp:g_atkmodule_uartrx_frame
 * @retval void

 *********************************************************************************/
uint8_t app_atkmodule_uartrx_polltst(void);

/***************************************************
 * @brief  
 * @param  void
 * @retval 
 ***************************************************/
uint8_t task_esp_rxmsg_poll(void);

///====End Codes-ESP==============================================================================End====

///====BSP-BTBLE==========================================================================================
/********************************************************
 * @brief       bsp
 * @param       buadrate: ATK-MODULE UART通讯波特率
 * @retval      Err_WIFI_NONE  : ATK-MODULE初始化成功
 *              Err_WIFI_ERROR: ATK-MODULE初始化失败
 ********************************************************/
void bsp_esp_devs_init(void);

/***************************************************
 * @brief  
 * @param  void
 * @retval 
 ***************************************************/
uint8_t task_esp_rxmsg_poll(void);

/***************************************************
 * @brief  
 * @param  void
 * @retval 
 ***************************************************/
uint8_t task_esp_txmsg_poll(void);

///====End BSP-BTBLE===============================================================================End====

#endif
/*----Endline : Full file-----------------------------------------------------------------------------------*/















