/**
 ****************************************************************************************************
 * @file         resdrv_cat1_uart.h
 * @author      Edwoy
 * @version     V1.0
 * @date        2022-06-21
 * @brief       ESPDev模块UART接口驱动代码
 * @license     Copyright (c) 2020-2032, 广州市星翼电子科技有限公司
 ****************************************************************************************************
 * @attention
 *
 * 实验平台:正点原子 F407电机开发板
 * 在线视频:www.yuanzige.com
 * 技术论坛:www.openedv.com
 * 公司网址:www.alientek.com
 * 购买地址:openedv.taobao.com
 *
 ****************************************************************************************************
 */

#ifndef _RESDRV_IOT_UART_H_
#define _RESDRV_IOT_UART_H_

#include "ThisProj_Conf.h"
#include "convert_path.h"
#include MCU_HEAD
#include SYS_HEAD
#include UTY_TYP_HEAD
#include "usart.h"
///--1atk_module-uart gpio--------------------------------------------------------------------------
//don`t use those if use the codes generated by cubemx
//#define ATK_MODULE_UART_TX_GPIO_PORT           GPIOB
//#define ATK_MODULE_UART_TX_GPIO_PIN            GPIO_PIN_10
//#define ATK_MODULE_UART_TX_GPIO_AF             GPIO_AF8_USART3
//#define ATK_MODULE_UART_TX_GPIO_CLK_ENABLE()   __HAL_RCC_GPIOB_CLK_ENABLE()

//#define ATK_MODULE_UART_RX_GPIO_PORT           GPIOB
//#define ATK_MODULE_UART_RX_GPIO_PIN            GPIO_PIN_11
//#define ATK_MODULE_UART_RX_GPIO_AF             GPIO_AF7_USART3
//#define ATK_MODULE_UART_RX_GPIO_CLK_ENABLE()   __HAL_RCC_GPIOB_CLK_ENABLE()

#define ATK_MODULE_UART_INTERFACE              USART3
#define ATK_MODULE_UART_IRQn                   USART3_IRQn
#define edwMODULE_UART_IRQHandler              USART3_IRQHandler
#define ATK_MODULE_UART_CLK_ENABLE()           __HAL_RCC_USART3_CLK_ENABLE()


/* UART收发缓冲大小 */
#define ATK_MODULE_RxBufSize            1024//  //3072
//#define ATK_MODULE_TxBufSize          64
///--1end atk_module-uart gpio-----------------------------------------------------------------1end---

///--atk_module-uart- paras---------------------------------------------------------------------------


#define PRP_MODULE          ATK_MODULE_UART_PRP
#define _atkmodule_init     MX_USART3_UART_Init
#define sMODULE             sUart3
#define MODULE_para         Uarts[sMODULE]
#define g_atkmodule_hdr     huart3  

extern uint8_t g_atkmodule_rxbuff[ATK_MODULE_RxBufSize] ;  
extern uint16_t g_atkmodule_rx_curcnt;   //  realtime count rx-datas , 
extern __IO Bool g_atkmodule_rxtkn_ovr ; //MODULE rx-token: be True if received a amount of datas over

///---End,atk_module-uart- paras----------------------------------------------------------------End----


/* 操作函数 */
void app_atkmodule_printf(char *fmt, ...);       /* ESPDev UART printf */
void app_atkmodule_uartrx_rst(void);             /* ESPDev UART重新开始接收数据 */
void app_atkmodule_init(uint32_t baudrate);      /* ESPDev UART初始化 */
uint8_t *app_atkmodule_rxmsg(void);       /* 获取ESPDev UART接收到的一帧数据 */
uint16_t app_atkmodule_rxmsg_length(void);   /* 获取ESPDev UART接收到的一帧数据的长度 */

///--atk_module-uart-2 base parameters-----------------------------------------------------------------
//---uart baudrate-----------------------------------------------------------------------
typedef enum
{
	 	UART_BAUDRATE_CHK    = 0xcf,           // check
    UART_BAUDRATE_9600   = 9600 ,          /* 9600bps */
    UART_BAUDRATE_19200  = 19200,          /* 19200bps */
    UART_BAUDRATE_38400  = 38400,          /* 38400bps */
    UART_BAUDRATE_57600  = 57600,          /* 57600bps */
    UART_BAUDRATE_115200 = 115200,         /* 115200bps */
    UART_BAUDRATE_230400 = 230400,         /* 230400bps */
	  UART_BAUDRATE_256000 = 256000,
	  UART_BAUDRATE_307200 = 307200 ,
	  UART_BAUDRATE_460800 = 460800,
	  UART_BAUDRATE_512000 = 512000,
	  UART_BAUDRATE_600000 = 600000,
	  UART_BAUDRATE_750000 = 750000,
} emEspUart_baud_t;
#define IS_VALID_UART_BAUDRATE_ESP(x)   ((9600   == x) || (19200  == x) || (38400  == x) || \
                                         (57600  == x) || (115200 == x) || (230400 == x) || \
                                         (256000 == x) || (307200 == x) || (460800 == x) || \
                                         (512000 == x) || (600000 == x) || (750000 == x))
//---end uart baudrate-------------------------------------------------------------end---

//---uart parity-------------------------------------------------------------------------
typedef enum
{
    ESP_UART_PARI_NONE = 0x00,        /* 无校验 */
	  ESP_UART_PARI_ODD  = 0x01,        /* 奇校验 */
    ESP_UART_PARI_EVEN = 0x02,        /* 偶校验 */	
	  ESP_UART_PARI_CHK  = 0xcf,       // check cmd
} emEspUart_pari_t;
#define IS_VALID_UART_PARI_ESP(x)   ((ESP_UART_PARI_NONE == x) ||  \
                                     (ESP_UART_PARI_EVEN == x) || ( ESP_UART_PARI_ODD == x))
//---end uart parity---------------------------------------------------------------end---

//---uart stopbit------------------------------------------------------------------------
typedef enum
{
    ESP_UART_STOP_1   = 0x01,     // 1位停止位 
    ESP_UART_STOP_1P5 = 0x02,     // 1.5位停止位 
	  ESP_UART_STOP_2   = 0x03,     // 2位停止位
    ESP_UART_STOP_CHK = 0xcf,	    // check cmd
} emEspUart_stop_t;   
#define IS_VALID_UART_STOP_ESP(x) ((ESP_UART_STOP_1   == x) ||   \
                                   (ESP_UART_STOP_1P5 == x) || (ESP_UART_STOP_2 == x))
//---end uart stopbit--------------------------------------------------------------end---

//---uart hardflow-----------------------------------------------------------------------
typedef enum
{
    ESP_UART_FLOW_CLOSE   = 0x00,      
    ESP_UART_FLOW_RTS     = 0x01,  
    ESP_UART_FLOW_CTS     = 0x02,  	
	  ESP_UART_FLOW_RTSCTS  = 0x03,  	
    ESP_UART_FLOW_CHK     = 0xcf,	 // check cmd
} emEspUart_hardflow_t;
#define IS_VALID_UART_FLOW_ESP(x)  ((ESP_UART_FLOW_CLOSE  == x) || (ESP_UART_FLOW_RTS  == x) || \
                                    (ESP_UART_FLOW_RTSCTS == x) || (ESP_UART_FLOW_CTS  == x))     
//---end uart hardflow--------------------------------------------------------------end---

//---uart hardflow-----------------------------------------------------------------------
typedef enum
{
    ESP_UART_BITS_5   = 0x05,      
    ESP_UART_BITS_6   = 0x06,  
    ESP_UART_BITS_7   = 0x07,  	
	  ESP_UART_BITS_8   = 0x08,  	
    ESP_UART_BITS_CHK = 0xcf,	 // check cmd
} emEspUart_databits_t;
#define IS_VALID_UART_BITS_ESP(x)  ((ESP_UART_BITS_5 == x) || (ESP_UART_BITS_6  == x) || \
                                    (ESP_UART_BITS_7 == x) || (ESP_UART_BITS_8  == x))                              
//---end uart hardflow--------------------------------------------------------------end---

///--end atk_module-uart-2 base parameters--------------------------------------------------------end---

#endif
/*----Endline : Full file-------------------------------------------------------------------------------------All_End---*/