/******************************************************************************************************
 * @file        lmbt.h
 * @author      Edwoy
 * @version     V1.0
 * @date        2021-10-27
 * @brief       Bluetooth&BLE drive h of serialport communication
 * @license     Copyright (c) 2020-2032
 ****************************************************************************************************
 * @attention
 ****************************************************************************************************
 * @note
 *    1 Default hard
          platform: ATK-DMF407
          module : BT-11 of LM(www.lbluetooth.com)			
 ****************************************************************************************************
 * @update
 *   V1.0 20211027 the orgn version from ATK-DMF407
 *
 ****************************************************************************************************
 */

#ifndef _CPT_LMBT_H_
#define _CPT_LMBT_H_

#include "ThisProj_Glb.h"
#include SYS_HEAD
#include UART_HEAD
#include RES_BTBLE_HEAD   //"./component/spBtBle/lmbt/res_lmbt_uart.h"
#include UTY_BTBLE_HEAD  //"./component/spBtBle/UTY/utyBtBle.h"
 

///====Codes-LMBT=========================================================================================
	
/**
 * @brief   handle , interrupt mode
            validated 
 * @note  
       -1-, used at etf_tsk_sysrun4() in project.c   
 * @retval  无
 */
uint8_t app_handle_lmbtdevsta_poll(uint8_t* ,sttLMBT_DevParas_t* );

/*********************************************
 * @brief       ATK-MODULE AT test
 * @param       无
 * @retval      Err_BTBLE_NONE     : success
 *              Err_BTBLE_TIMEOUT: error
 *********************************************/
uint8_t app_lmbt_at_test(void);

/*********************************************************************************
 * @brief  Check workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @notice 
           -1-,Must base on usart.h/c generated by cbx
 * @retval void
 *********************************************************************************/
void app_lmbt_init(void) ;

/*********************************************************************************
 * @brief  Check workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval void
 *********************************************************************************/
uint8_t app_lmbt_check_wkmd(void);

/*********************************************************************************
 * @brief  Set ble-slave workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval void
 *********************************************************************************/
uint8_t app_lmbt_setwkmd_bleslv(void);

/*********************************************************************************
 * @brief  Set ble-master workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_BTBLE_NONE  : success
 *         Err_BTBLE_ERROR: error
 *********************************************************************************/
uint8_t app_lmbt_setwkmd_blemtr(void);

/*******************************************************************
 * @brief       Set RF-power grade for LM`s bluetooth&ble dev 
                using serialport(UART/USART)-interface
                LM(www.lbluetooth.com)
 * @param       pwr, enum RF-power grade
                    check it in res_spBTBLE.h
 * @retval      Err_BTBLE_NONE  : 
 *              Err_BTBLE_ERROR:
 *************************************************************/
uint8_t app_lmbt_set_rfpower(emLMBT_PwrGrd_t pwr);

/*******************************************************************
 * @brief       Set uart`s baudrate for LM`s bluetooth&ble dev 
                using serialport(UART/USART)-interface
                LM(www.lbluetooth.com)
 * @param       baudrate, checked em_lmbt_uart_baud_t 
                in res_spBTBLE.h
 * @retval      Err_BTBLE_NONE  : 
 *              Err_BTBLE_ERROR: 
 ******************************************************************/
uint8_t app_lmbt_set_uart_baud(em_lmbt_uart_baud_t  baudrate);

/*******************************************************************
 * @brief       Set uart`s baudrate for LM`s bluetooth&ble dev 
                using serialport(UART/USART)-interface
                LM(www.lbluetooth.com)
 * @param       baudrate, checked em_lmbt_uart_baud_t 
                in res_spBTBLE.h
 * @retval      Err_BTBLE_NONE  : ATK-MODULE进入配置模式成功
 *              Err_BTBLE_ERROR: ATK-MODULE进入配置模式失败
 ******************************************************************/
uint8_t app_lmbt_set_uart_stop(em_lmbt_uart_stop_t stop);

/*******************************************************************
 * @brief       设置ATK-MODULE串口参数
 * @param       baudrate: 波特率
 *              data    : 数据位
 *              pari    : 校验位
 *              stop    : 停止位
 * @retval      Err_BTBLE_NONE   : 设置ATK-MODULE串口参数成功
 *              Err_BTBLE_ERROR : 设置ATK-MODULE串口参数失败
 *              Err_BTBLE_INVAL: 函数参数错误
                           em_lmbt_uart_pari_t     pari,     \
                           em_lmbt_uart_stop_t     stop
 ******************************************************************/
uint8_t app_lmbt_set_uart_flow(em_lmbt_uart_stop_t flow);


/*******************************************************************
 * @brief       设置ATK-MODULE串口参数
 * @param       baudrate: 波特率
 *              data    : 数据位
 *              pari    : 校验位
 *              stop    : 停止位
 * @retval      Err_BTBLE_NONE   : 设置ATK-MODULE串口参数成功
 *              Err_BTBLE_ERROR : 设置ATK-MODULE串口参数失败
 *              Err_BTBLE_INVAL: 函数参数错误
                           em_lmbt_uart_pari_t     pari,     \
                           em_lmbt_uart_stop_t     stop
 ******************************************************************/
uint8_t app_lmbt_set_uart_parity(em_lmbt_uart_stop_t pari);

/*********************************************************************************
 * @brief  Set SPP-Slave workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_BTBLE_NONE  : success
 *         Err_BTBLE_ERROR: error
 *********************************************************************************/
uint8_t app_lmbt_setwkmd_sppslv(void);

/*********************************************************************************
 * @brief  Set SPP-BLE-Slave double workmode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_BTBLE_NONE  : success
 *         Err_BTBLE_ERROR: error
 *********************************************************************************/
uint8_t app_lmbt_setwkmd_dualslv_sppble(void);

/*********************************************************************************
 * @brief   Disconnect LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_BTBLE_NONE  : success
 *         Err_BTBLE_ERROR: error
 *********************************************************************************/
uint8_t app_lmbt_disconnect(void) ;

/*********************************************************************************
 * @brief   Check powermode  for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_BTBLE_NONE  : success
 *        
 *********************************************************************************/
uint8_t app_lmbt_check_powermode(void) ;
	
/*********************************************************************************
 * @brief   Set powermode and check it for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  dptm,
             0,Auto enter lowpower mode
             1, normal power mode
             0xcf,=CHECK_CMD_BTBLE,check 
 * @retval Err_BTBLE_NONE  : success
 *         Err_BTBLE_ERROR: error
  
 *********************************************************************************/
uint8_t app_lmbt_set_powermode(emLMBT_PwrMd_t pwr) ;

/*********************************************************************************
 * @brief  Exit lowpower mode for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_BTBLE_NONE  : success
 *         Err_BTBLE_ERROR: error
  
 *********************************************************************************/
uint8_t app_lmbt_exit_lowpower(void) ;

/*********************************************************************************
 * @brief  Set time entering lowpower for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  tm,time after that enter lowpower
             0,error
             others,enter lowpower after dptm s
 * @retval Err_BTBLE_NONE  : success
 *         Err_BTBLE_ERROR: error
  
 *********************************************************************************/
uint8_t app_lmbt_settime_intolowpower( uint8_t tm) ;

/*********************************************************************************
 * @brief   Enter deepsleep and check dptim for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  dptm,time to enter deepsleep
             0,error
             0xcf,=CHECK_CMD_BTBLE,check 
             others(IS_VALID_DEEPSLP_LMBT) ,time to enter deepsleep
 * @retval Err_BTBLE_NONE  : success
 *         Err_BTBLE_ERROR: error
  
 *********************************************************************************/
uint8_t app_lmbt_enter_deepsleep( uint8_t dptm) ;

/*********************************************************************************
 * @brief  Exit deepsleep for LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param  void
 * @retval Err_BTBLE_NONE  : success
 *         Err_BTBLE_ERROR: error
  
 *********************************************************************************/
uint8_t app_lmbt_exit_deepsleep(void) ;

/**
 * @brief       设置ATK-MODULE b-type name
 * @param       name: 蓝牙名称
                  NULL,check namb
                  others,b-type name
 * @retval      Err_BTBLE_NONE  : 设置ATK-MODULE蓝牙名称成功
 *              Err_BTBLE_ERROR: 设置ATK-MODULE蓝牙名称失败
 */
uint8_t app_lmbt_set_name(char *name);


/**
 * @brief       设置ATK-MODULE b-type name
 * @param       name: 蓝牙名称
                  NULL,check namb
                  others,b-type name
 * @retval      Err_BTBLE_NONE  : 设置ATK-MODULE蓝牙名称成功
 *              Err_BTBLE_ERROR: 设置ATK-MODULE蓝牙名称失败
 */
uint8_t app_lmbt_set_namb(char *name);

/**************************************************************
 * @brief       设置ATK-MODULE串口参数
 * @param       baudrate: 波特率
 *              data    : 数据位
 *              pari    : 校验位
 *              stop    : 停止位
                flow ,   hardflow
 * @retval      Err_BTBLE_NONE   : 设置ATK-MODULE串口参数成功
 *              Err_BTBLE_ERROR : 设置ATK-MODULE串口参数失败
 *              Err_BTBLE_INVAL: 函数参数错误
 ***************************************************************/
uint8_t app_lmbt_config_uart(em_lmbt_uart_baud_t  baudrate, \
                             em_lmbt_uart_pari_t      pari,     \
                             em_lmbt_uart_stop_t      stop,     \
                             em_lmbt_uart_hardflow_t  flow      );

/****************************************************************
 * @brief       Reset the lmbt btble-dev
 * @param       void
 * @retval      Err_BTBLE_NONE  : 设置ATK-MODULE蓝牙名称成功
 *              Err_BTBLE_ERROR: 设置ATK-MODULE蓝牙名称失败
 **************************************************************/
uint8_t app_lmbt_dev_rst(void);

/*********************************************************************************
 * @brief  Poll-proccess for UART/USART rx of LM`s bluetooth&ble dev 
           using serialport(UART/USART)-interface
           LM(www.lbluetooth.com)
 * @param   rxframe,
                exp:g_atkmodule_uartrx_frame
 * @retval void

 *********************************************************************************/
uint8_t app_atkmodule_uartrx_polltst(void);

/***************************************************
 * @brief  
 * @param  void
 * @retval 
 ***************************************************/
uint8_t task_lmbt_rxmsg_poll(void);

///====End Codes-LMBT==============================================================================End====

///====BSP-BTBLE==========================================================================================
/********************************************************
 * @brief       bsp
 * @param       buadrate: ATK-MODULE UART通讯波特率
 * @retval      Err_BTBLE_NONE  : ATK-MODULE初始化成功
 *              Err_BTBLE_ERROR: ATK-MODULE初始化失败
 ********************************************************/
void bsp_lmbt_devs_init(void);

/***************************************************
 * @brief  
 * @param  void
 * @retval 
 ***************************************************/
uint8_t task_lmbt_rxmsg_poll(void);

/***************************************************
 * @brief  
 * @param  void
 * @retval 
 ***************************************************/
uint8_t task_lmbt_txmsg_poll(void);

///====End BSP-BTBLE===============================================================================End====

#endif
/*----Endline : Full file-----------------------------------------------------------------------------------*/















