/************************************************************************************
 * @file   project.c
					main codes is etf_tsk_sysrun1(void)
					validate Aliyun iot platform Communication between targetboard(atk-dmf407)-esp8266 and  Aliyun IoT Studio->Webapp
					validate Aliyun iot platform`s thing->property(exp:current,volt,powerswitch,temperature...) post and post+reply
					based on Mqtt at Aliyun
				  generated by cubemx for ATK-DMF407
 * @author Edwoy
 * @version validated,[+] smartconfig in app_mqtt_init_v2 
 * @date    2023.6.9, project is all validated 
 * @validated items 
 			 Aliyun brokers <==> AP route <==> ESPdev<-->uart4(atkmodule)of ATK-DMF407 ,usart1 <==> PC	
			-1-,valid broker
 			-1-,valid test
    		 1.1 Aliyun iot platform test
				   1.1.1  broker1 : https://iot.console.aliyun.com/devices/a1QSdqL2OX7/esp8266/1   
			         TB1-->product:wifi-iot ; device : esp8266
				   1.1.2 broker2: https://iot.console.aliyun.com/devices/a1OL5KrWqJA/adcdev1/1
				       TB1-->product:product1; device : adcdev1
			  1.2 Communication between targetboard(atk-dmf407)-esp8266 and  Aliyun IoT Studio->Webapp
				    broker3: https://iot.console.aliyun.com/devices/a1BQHA5vPYl/home1/1 	
			   	  TB1-->product:smathome1; device : home1
						IoT Studio Webapp: https://studio.iot.aliyun.com/web/a123dTTZzeeGYWLQ/app/a120MRCRN57qCetJ/edit
						study video,https://www.bilibili.com/video/BV1Rv4y1P7M3/?spm_id_from=333.337.search-card.all.
				                  click&vd_source=08eea1805655250a87b323b6cedd4b01 
			-2-, validated route:
     			AP1 route:EDW201X and AP2 route:OOPEN-1(4G converted to WiFi-2.4G)
			-3-, 
 ***********************************************************************************							
 * @notice
       -1-, After successful connection,  cannot be disconnected.
   					Once disconnected (including active disconnection by the usr or phone screen), 
						it must rebuild communication
					
            			 
  ***********************************************************************************							
 * @note，项目变更等 
      -2-,steps
			    2.1 base, 
					  2.1.1 Download the Ai-thinker Mqtt-firmware v1112 to esp8266
						      RstGpio and DownloadGpio(IO_0) are float or Set high
					  2.1.2 cubemx generates base codes
					    Link the right COMx of rs232 DBCOM , codes build --> download --->
            2.1.3 Use main-cp.c & stm32f4xx_it-cp.c , delate or disable main.c & stm32f4xx_it.c
					    If there are any updates, copy and paste the updated content to xxx-cp.c
							because  main() of main.c must disable or delate MX_FSMC_Init() 
					2.2 After about 10 seconds of powering on the target board,
						  Mqtt will complete initialization and subscription (all 8 steps)
							
					2.3  communication
					  2.3.1 press BTN0 --> Publish JsonMsg to Mqtt->hosturl
					  2.3.2 app_atkmodule_uartrxmsg_poll() print the sub-JsonMsg from broker hosturl
						2.3.3 use dbocm send cmd to espdev by etf_dbcomtsk_esp()   
							  
			-1-,Mqtt
         1.1 state
           1.1.1 Unactivated means that the Alibaba Cloud device has never been connected to a WiFi device (such as ESP8266) 
					        and needs to be successfully connected to the Alibaba Cloud device once
                 app_mqtt_init() will provide configuration for the WiFi device
          1.1.2 Offline, there have been successful connections, but the WiFi device has been shut down
          1.1.3 Online, Alibaba Cloud broker is connecting to this WiFi device, 
					      so the WiFi device can publish and subscribe to messages				 
				1.2 

			-0-,use AC6.19, C11, FW_F4_V1.26.2，keilv5.38.0, bare run
         0.1 DBCOM(usart1) 
			        fills rx-datas in DBCOM_UX_IRQHandler
				    	shell_uart drv use V1.5
				 0.2 LCD 3.5``, 320*380					
 ************************************************************************************/

#include "ThisProj_Glb.h"

///--NetAssist of PC ----------------------------------------------------------------------
//#define DEMO_TCP_SERVER_IP      "192.168.1.6" // Upper`s ip 
//#define DEMO_TCP_SERVER_PORT    "6065"        // 
///--End NetAssist of PC------------------------------------------------------------End----

///--AP1 route:EDW201X(validated)----------------------------------------------------------
#define DEMO_WIFI_SSID          "EDW201X"     // 
#define DEMO_WIFI_PWD           "txhd349874"  //
/*--NetAssist of phone-Z40Spro -----------------------------------------------------*/
#define DEMO_TCP_SERVER_IP      "192.168.1.7" // Upper`s ip 
#define DEMO_TCP_SERVER_PORT    "6067"        // 
///--End AP1 route:EDW201X ---------------------------------------------------------End----

///--AP2 route:OOPEN-1(validated)----------------------------------------------------------
//#define DEMO_WIFI_SSID          "OOPEN-1"     // 
//#define DEMO_WIFI_PWD           "refond05891"  //
///*--NetAssist of phone-Z40Spro --------------------------------------------------*/
//#define DEMO_TCP_SERVER_IP      "192.168.1.147" // Upper`s ip 
//#define DEMO_TCP_SERVER_PORT    "7063"        // 
///--End AP2 route:OOPEN-1 ---------------------------------------------------------End----

/**
 * @brief       显示IP地址
 * @param       无
 * @retval      无
 */
static void task_show_ip(char *buf)
{
    printf("IP: %s\r\n", buf);
    lcd_show_string(60, 151, 128, 16, 16, buf, BLUE);
}

static void etf_prjtsk_sysrun(uint32_t p)
{
	if(p < 10000)
	{
		p = 10000;
	}
  static uint32_t tmpvar = 0;    	
	if(NULL == tmpvar++ % p)
	{
		SYSRUN_LED_TGG();
		stkdly_ms(10);			
	}	
}

#define __pjf_mqtt_tstdev  g_atkmoudle_mqttdev_home1  // g_atkmoudle_mqttdev_home1  //g_atkmoudle_esp_dev1  // 

/***********************************************************************
 * @brief  (validated)例程演示入口函数
 * @param       无
 * @retval      无
        pjf_dbcom_cmdpoll();
				
 **********************************************************************			
//volidated-1:
        switch (btns_monitor(BtnTrg_JpE))
        {
            case PrsFlg_B0:	 //valid
							  app_esp_autoconn_enable();
							  app_esp_set_cwmode(EspCWM_Sta);

						    app_esp_link_ap_v2(&__pjf_mqtt_tstdev,0);
                app_esp_cipstatus(&__pjf_mqtt_tstdev)	;				
                break;

            case PrsFlg_B1: //valid
							  if(Err_WIFI_NONE ==  app_espdev_sftrst_v2(&__pjf_mqtt_tstdev))
								{
									__NOP();
								}
                break;

            case PrsFlg_B2: //valid
						  	app_esp_set_cwmode(EspCWM_Sta);
                if(Err_WIFI_NONE == app_esp_smartconfig(&__pjf_mqtt_tstdev))
								{
									stkdly_ms(150);
									app_esp_stop_smartconfig(&__pjf_mqtt_tstdev);
								}
                break;	
						
            default: break;
        }
	****************************************************************
	  valid identifiers and vars of thing	
		const char* thing_idr1="LightCurrent";
		const char* thing_idr2="LightVolt";
		const char* thing_idr3="PowerSwitch_1";
		const char* thing_idr4="temperature";
		
		int   temperature  = 29;
		uint8_t  pwrswh    = 0 ; //true-->open; false-->close
		float volt        = 3.27;
		float current     = 0.22;
 ************************************************************************/
void etf_tsk_sysrun1(void)
{
    static char ret = 50;
	  uc32_t tock = 100000;
	  char tmp_pubmsg[256] = {0};
    static uint32_t tmpvar = 0;   	
	  
		app_mqtt_init_v2(&__pjf_mqtt_tstdev);
		
		sprintf(tmp_pubmsg,"{\\\"method\\\":\\\"thing_idr.event.property.post\\\"\\,\\\"params\\\":{\\\"%s\\\":%4.2f\\,\\\"%s\\\":%4.2f\\,\\\"%s\\\":%d\\,\\\"%s\\\":%d}}",
													thing_idr1,current,thing_idr2,volt,thing_idr3,pwrswh,thing_idr4,temperature);		

		app_mqtt_publish_freemsg(__pjf_mqtt_tstdev.topic_tpp_pub, tmp_pubmsg);
		

		
		printf("mqtt->thing_idr property topic: %s\r\n",tmp_pubmsg);
		
    while (1)
    {        
        switch (btns_monitor(BtnTrg_JpE))
        {
            case PrsFlg_B0:	 //valid,
								current     += 0.05;
								volt        += 0.15;
								temperature += 1 ;
						    sprintf(tmp_pubmsg,"{\\\"method\\\":\\\"thing_idr.event.property.post\\\"\\,\\\"params\\\":{\\\"%s\\\":%4.2f\\,\\\"%s\\\":%4.2f\\,\\\"%s\\\":%d}}",
		                                  thing_idr1,current,thing_idr2,volt,thing_idr4,temperature);		
	              app_mqtt_publish_freemsg(__pjf_mqtt_tstdev.topic_tpp_pub, tmp_pubmsg);
						
						
                break;

            case PrsFlg_B1: //valid
								current     -= 0.05;
								volt        -= 0.15;
								temperature -= 1 ;
						    sprintf(tmp_pubmsg,"{\\\"method\\\":\\\"thing_idr.event.property.post\\\"\\,\\\"params\\\":{\\\"%s\\\":%4.2f\\,\\\"%s\\\":%4.2f\\,\\\"%s\\\":%d}}",
		                                  thing_idr1,current,thing_idr2,volt,thing_idr4,temperature);		

	              app_mqtt_publish_freemsg(__pjf_mqtt_tstdev.topic_tpp_pub, tmp_pubmsg);
                break;

            case PrsFlg_B2: //valid
								sprintf(tmp_pubmsg,"{\\\"method\\\":\\\"thing_idr.event.property.post\\\"\\,\\\"params\\\":{\\\"%s\\\":%d\\}}",
											  thing_idr3,pwrswh);		
						     app_mqtt_publish_freemsg(__pjf_mqtt_tstdev.topic_tpp_pub, tmp_pubmsg);
                break;	
						
            default: break;
        }
				
				app_mqtt_alyzmsg_webapp_swh(&__pjf_mqtt_tstdev);
				app_espdev_linksta_poll(&__pjf_mqtt_tstdev);
				app_atkmodule_uartrxmsg_poll();
        etf_dbcomtsk_esp(&__pjf_mqtt_tstdev);		
				etf_prjtsk_sysrun( tock) ; //tock = 10000,default
        
    }
}
/*----Endline : Full file----------------------------------------------------------------------All_End-----*/