/*******************************************************************************************************************************
 * @file   project.c
					main codes is etf_taskHome(void)
					validate BSPgpios(Leds&Btns),DBCOM,i2c&pcf8574
				  generated by cubemx for ApolloF429
 * @author Edwoy
 * @version V1.0,validated
 * @date    2023.6.30, project is all validated 
 * @validated items 		 
			-1-,valid Leds&Btns&DBCOM,i2c&pcf8574
 ***********************************************************************************							
 * @notice
       -1-
           			 
  ***********************************************************************************							
 * @note，项目变更等 
			-1-,steps

			-0-,use AC6.16, C11, FW_F4_V1.26.2，keilv5.36.0, bare run
         0.1 DBCOM(usart1) 
			        fills rx-datas in DBCOM_UX_IRQHandler
				    	shell_uart drv use V1.5
				 0.2 
		
 *******************************************************************************************************************************/

#include "ThisProj_Glb.h"

///--NetAssist of PC ----------------------------------------------------------------------
//#define DEMO_TCP_SERVER_IP      "192.168.1.6" // Upper`s ip 
//#define DEMO_TCP_SERVER_PORT    "6065"        // 
///--End NetAssist of PC------------------------------------------------------------End----

///--AP1 route:EDW201X(validated)----------------------------------------------------------
#define DEMO_CAT1_SSID          "EDW201X"     // 
#define DEMO_CAT1_PWD           "txhd349874"  //
/*--NetAssist of phone-Z40Spro -----------------------------------------------------*/
#define DEMO_TCP_SERVER_IP      "192.168.1.7" // Upper`s ip 
#define DEMO_TCP_SERVER_PORT    "6067"        // 
///--End AP1 route:EDW201X ---------------------------------------------------------End----

///--AP2 route:OOPEN-1(validated)----------------------------------------------------------
//#define DEMO_CAT1_SSID          "OOPEN-1"     // 
//#define DEMO_CAT1_PWD           "refond05891"  //
///*--NetAssist of phone-Z40Spro --------------------------------------------------*/
//#define DEMO_TCP_SERVER_IP      "192.168.1.147" // Upper`s ip 
//#define DEMO_TCP_SERVER_PORT    "7063"        // 
///--End AP2 route:OOPEN-1 ---------------------------------------------------------End----

/**
 * @brief       显示IP地址
 * @param       无
 * @retval      无
 */
//static void task_show_ip(char *buf)
//{
//    printf("IP: %s\r\n", buf);
//    lcd_show_string(60, 151, 128, 16, 16, buf, BLUE);
//}

static void _prjpoll_sysrun(uint32_t p)
{
	if(p < 60)
	{
		p = 60;
	}
  static uint32_t tmpvar = 0;    	
	if(NULL == tmpvar++ % p)
	{
		SYSRUN_LED_TGG();
	}	
	stkdly_ms(5);
}

/***********************************************************************
 * @brief  (validated)例程演示入口函数
 * @param       无
 * @retval      无
        pjf_dbcom_cmdpoll();
				
 **********************************************************************			
    while (1)
    {        
        switch (btns_monitor(BtnTrg_JpE))
        {
            case PrsFlg_B0:	 //valid,

                pcf8574_io_wt(ExtIO_Beep,0);
                break;

            case PrsFlg_B1: //valid
			          pcf8574_io_wt(ExtIO_Beep,1);
                break;

            case PrsFlg_B2: //valid
                RED_LED_TGG();
                break;	

            case PrsFlg_WkUp: //valid
                printf("WkUp is pressed\r\n");

                break;	
						
            default: break;
        }
				
			
       _prjpoll_sysrun(0);
    }
 ************************************************************************/
void etf_taskHome(void)
{
/*   
  static char ret = 50;
    uc32_t tock = 100000;
    char tmp_pubmsg[256] = {0};
    static uint32_t tmpvar = 0;   	
	   */
		
   
    switch (btns_monitor(BtnTrg_JpE))
    {
        case PrsFlg_B0:	 //valid,

            pcf8574_io_wt(ExtIO_Beep,0);
            break;

        case PrsFlg_B1: //valid
                    pcf8574_io_wt(ExtIO_Beep,1);
            break;

        case PrsFlg_B2: //valid
            RED_LED_TGG();
            break;	

        case PrsFlg_WkUp: //valid
            printf("WkUp is pressed\r\n");

            break;	
                    
        default: break;
    }
            
        
    _prjpoll_sysrun(0);
  
}


/*----Endline : Full file------------------------------------------------------------------------All_End-----*/

/**
  * \valid espdevs
	 g_atkmoudle_mqttdev_home1  
	 g_atkmoudle_esp_dev1  
	 g_atkmoudle_esp_dev0 
	 g_atkmoudle_mqttdev_airdtr1 
#define __pjf_mqtt_tstdev  g_atkmoudle_mqttdev_airdtr1 
  */
