/*******************************************************************************************************************************
 * @file   project.c
					main codes is etf_taskHome(void)
					validate BSPgpios(Leds&Btns),DBCOM,i2c&pcf8574
				  generated by cubemx for ApolloF429
 * @author Edwoy
 * @version V1.0,verified
 * @date    2026.6.30, project is all verified 
 * @verified items 		 
			-1-,valid Leds&Btns&DBCOM,i2c&pcf8574
 ***********************************************************************************							
 * @notice
       -1-
           			 
  ***********************************************************************************							
 * @note，项目变更等 
			-1-,steps

			-0-,use AC6.16, C11, FW_F4_V1.26.2，keilv5.36.0, bare run
         0.1 DBCOM(usart1) 
			        fills rx-datas in DBCOM_UX_IRQHandler
				    	shell_uart drv use V1.5
				 0.2 
		
 *******************************************************************************************************************************/

#include "ThisProj_Glb.h"

///--NetAssist of PC ----------------------------------------------------------------------
//#define DEMO_TCP_SERVER_IP      "192.168.1.6" // Upper`s ip 
//#define DEMO_TCP_SERVER_PORT    "6065"        // 
///--End NetAssist of PC------------------------------------------------------------End----

///--AP1 route:EDW201X(verified)----------------------------------------------------------
#define DEMO_CAT1_SSID          "EDW201X"     // 
#define DEMO_CAT1_PWD           "txhd349874"  //
/*--NetAssist of phone-Z40Spro -----------------------------------------------------*/
#define DEMO_TCP_SERVER_IP      "192.168.1.7" // Upper`s ip 
#define DEMO_TCP_SERVER_PORT    "6067"        // 
///--End AP1 route:EDW201X ---------------------------------------------------------End----

///--AP2 route:OOPEN-1(verified)----------------------------------------------------------
//#define DEMO_CAT1_SSID          "OOPEN-1"     // 
//#define DEMO_CAT1_PWD           "refond05891"  //
///*--NetAssist of phone-Z40Spro --------------------------------------------------*/
//#define DEMO_TCP_SERVER_IP      "192.168.1.147" // Upper`s ip 
//#define DEMO_TCP_SERVER_PORT    "7063"        // 
///--End AP2 route:OOPEN-1 ---------------------------------------------------------End----

/***********************************************
 * @brief       显示IP地址
 * @param       无
 * @retval      无
 ***********************************
//static void task_show_ip(char *buf)
//{
//    printf("IP: %s\r\n", buf);
//    lcd_show_string(60, 151, 128, 16, 16, buf, BLUE);
//}

 ********************************************/

 /*****************************************
  * @brief  系统时钟滴答
  * 
  ****************************************/
static void _f_poll_sys_ticktock(uint32_t p)
{

  static uint32_t tmpvar = 0;   
  static uint32_t tTock = 10;
	if(p < 10000){
		tTock = 10000;
	}
	else{
		tTock = p;
	}
  
	if(0 == tmpvar++ % tTock){
		SYSRUN_LED_TGG();
		//printf("System pace\r\n");
	}	

}

/***********************************************************************
 * @brief  (verified)例程演示入口函数
 * @param  pArg
 * @retval  void
        pjf_dbcom_cmdpoll();
 *************************************************
  //verifying...
#if G_USE_SAMP_GPIO ==  G_USE_SAMP_GPIO_EDW

 //s>---keys poll-----------------
   //invalid:
   app_samp_1key_pollhdr(&g_samp_keys[KeyID_Btn0]);
    app_samp_1key_pollhdr(&g_samp_keys[KeyID_Btn1]);
    app_samp_1key_pollhdr(&g_samp_keys[KeyID_Btn2]); //invalid:
   app_samp_1key_pollhdr(&g_samp_keys[KeyID_WkUp]);  //invalid:
     //  app_samp_allkeys_pollhdr(g_samp_keys);  
   // app_samp_allkeys_scan(1);
//e<---Keys poll-----------------	
#endif //<<G_USE_SAMP_GPIO ==  G_USE_SAMP_GPIO_EDW>

 **********************************************************************/
void etf_taskHome(void* pArg)
{
    static unsigned int tArg = 0;
    tArg =  *(unsigned int *)pArg;

//s>--keys poll------------------------------------------    
#if G_USE_SAMP_GPIO ==  G_USE_SAMP_GPIO_AFL     
    //s>--armfly keys poll-----------------
    //verified,valids
   sample_afl_keys();
    bsp_KeyScan10ms();
    //e<---armfly keys poll-----------------
#endif //<<G_USE_SAMP_GPIO ==  G_USE_SAMP_GPIO_AFL>


//e<--Keys poll----------------------------------------------

    _f_poll_sys_ticktock(tArg);    

}//<void etf_taskHome(void *pArg)>

/********************Verified Items**************************************
//s>---item1: KeyID_Btn0-----------------
    app_samp_1key_pollhdr(&g_samp_keys[KeyID_Btn0]);
//e<---item1: KeyID_Btn0-----------------

    //s>--armfly keys poll-----------------
#if G_USE_SAMP_GPIO ==  G_USE_SAMP_GPIO_AFL     
    //s>--armfly keys poll-----------------
    //verified,valids
   sample_afl_keys();
    bsp_KeyScan10ms();
    //e<---armfly keys poll-----------------
#endif //<<G_USE_SAMP_GPIO ==  G_USE_SAMP_GPIO_AFL>
    //e<---armfly keys poll-----------------
*********************Verified Items**************************************/

///s>==custom keys handlers======================================================
//edwoy260502---
/***********************************
 * @brief       按键处理函数
 * @param       pID:按键ID
 * @param       pArg:按键参数
 * @retval      
 *      -1,pID不匹配
 *      0,处理成功
 ***********************************/
char app_custom_btn0(void* pArg)
{
    pArg = pArg;
//    pcf8574_io_wt(ExtIO_Beep,0);
//	  RED_LED_TGG();
	  printf("KEY_BTN0 is pressed\r\n");
    return 0;
}
/***********************************
 * @brief       按键处理函数
 * @param       pID:按键ID
 * @param       pArg:按键参数
 * @retval
 *      -1,pID不匹配
 *      0,处理成功
 ************************************/
char app_custom_btn1(void* pArg)
{
    pArg = pArg;

	  printf("KEY_BTN1 is pressed,gen div0 fault\r\n");
    return 0;
}
char app_custom_btn2(void* pArg)
{
    pArg = pArg;
//    RED_LED_TGG();
    printf("KEY_BTN2 is pressed,gen div0 fault\r\n");
   // fault_test_by_div0() ;    
    return 0;
}
char app_custom_wkup(void* pArg)
{
    pArg = pArg;
    printf("WkUp is pressed,gen unalign fault\r\n");
 //   fault_test_by_unalign() ;
    return 0;
}
///e<==custom keys handlers=============================================================================

////----Endline : Full file--------------------------------------------------------------------------------------All_End----

/**
  * \valid espdevs
	 g_atkmoudle_mqttdev_home1  
	 g_atkmoudle_esp_dev1  
	 g_atkmoudle_esp_dev0 
	 g_atkmoudle_mqttdev_airdtr1 
#define __pjf_mqtt_tstdev  g_atkmoudle_mqttdev_airdtr1 
  */
